// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x490
			namespace C_INIT_InitFloat /*: public CS2::particles::CParticleFunctionInitializer*/ {
				constexpr std::ptrdiff_t m_InputValue = 0x1c8; // particleslib::CPerParticleFloatInput m_InputValue; |  Schema_DeclaredClass | Size: 0x160
				constexpr std::ptrdiff_t m_nOutputField = 0x328; // particles::ParticleAttributeIndex_t m_nOutputField; |  Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_nSetMethod = 0x32c; // particles::ParticleSetMethod_t m_nSetMethod; |  Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_InputStrength = 0x330; // particleslib::CPerParticleFloatInput m_InputStrength; |  Schema_DeclaredClass | Size: 0x160
			}
		}
	}
}
