// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x1D0
			namespace C_INIT_RandomSecondSequence /*: public CS2::particles::CParticleFunctionInitializer*/ {
				constexpr std::ptrdiff_t m_nSequenceMin = 0x1c8; // int32_t m_nSequenceMin; |  0x1c8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nSequenceMax = 0x1cc; // int32_t m_nSequenceMax; |  0x1cc | Schema_Builtin | Size: 0x4
			}
		}
	}
}
