// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x238
			namespace C_OP_RemapTransformOrientationToYaw /*: public CS2::particles::CParticleFunctionOperator*/ {
				constexpr std::ptrdiff_t m_TransformInput = 0x1c0; // particleslib::CParticleTransformInput m_TransformInput; |  Schema_DeclaredClass | Size: 0x68
				constexpr std::ptrdiff_t m_nFieldOutput = 0x228; // particles::ParticleAttributeIndex_t m_nFieldOutput; |  Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flRotOffset = 0x22c; // float32 m_flRotOffset; |  0x22c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flSpinStrength = 0x230; // float32 m_flSpinStrength; |  0x230 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
