// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x1E0
			namespace C_OP_FadeIn /*: public CS2::particles::CParticleFunctionOperator*/ {
				constexpr std::ptrdiff_t m_flFadeInTimeMin = 0x1d0; // float32 m_flFadeInTimeMin; |  0x1d0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFadeInTimeMax = 0x1d4; // float32 m_flFadeInTimeMax; |  0x1d4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFadeInTimeExp = 0x1d8; // float32 m_flFadeInTimeExp; |  0x1d8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bProportional = 0x1dc; // bool m_bProportional; |  0x1dc | Schema_Builtin | Size: 0x1
			}
		}
	}
}
