// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x210
			namespace C_OP_RemapCPtoVector /*: public CS2::particles::CParticleFunctionOperator*/ {
				constexpr std::ptrdiff_t m_nCPInput = 0x1c0; // int32_t m_nCPInput; |  0x1c0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nFieldOutput = 0x1c4; // particles::ParticleAttributeIndex_t m_nFieldOutput; |  Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_nLocalSpaceCP = 0x1c8; // int32_t m_nLocalSpaceCP; |  0x1c8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_vInputMin = 0x1cc; // GlobalTypes::Vector m_vInputMin; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vInputMax = 0x1d8; // GlobalTypes::Vector m_vInputMax; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vOutputMin = 0x1e4; // GlobalTypes::Vector m_vOutputMin; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vOutputMax = 0x1f0; // GlobalTypes::Vector m_vOutputMax; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flStartTime = 0x1fc; // float32 m_flStartTime; |  0x1fc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flEndTime = 0x200; // float32 m_flEndTime; |  0x200 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flInterpRate = 0x204; // float32 m_flInterpRate; |  0x204 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nSetMethod = 0x208; // particles::ParticleSetMethod_t m_nSetMethod; |  Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bOffset = 0x20c; // bool m_bOffset; |  0x20c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bAccelerate = 0x20d; // bool m_bAccelerate; |  0x20d | Schema_Builtin | Size: 0x1
			}
		}
	}
}
