// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particles {
			// Class size: 0x680
			namespace VecInputMaterialVariable_t /**/ {
				constexpr std::ptrdiff_t m_strVariable = 0x0; // GlobalTypes::CUtlString m_strVariable; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_vecInput = 0x8; // particleslib::CParticleCollectionVecInput m_vecInput; |  Schema_DeclaredClass | Size: 0x678
			}
		}
	}
}
