// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/soundsystem_voicecontainers/CVoiceContainerBase.hpp>
#include <SDK/soundsystem_voicecontainers/CSoundContainerReference.hpp>



namespace CS2 {
	namespace soundsystem_voicecontainers {
		class CVoiceContainerBlender : public CS2::soundsystem_voicecontainers::CVoiceContainerBase {
		public:
			soundsystem_voicecontainers::CSoundContainerReference m_firstSound; // 0xb8 | Schema_DeclaredClass | Size: 0x18
			soundsystem_voicecontainers::CSoundContainerReference m_secondSound; // 0xd0 | Schema_DeclaredClass | Size: 0x18
			float32 m_flBlendFactor; // 0xe8 | Schema_Builtin | Size: 0x4
			S2_PAD(0x4); // End padding
		};
		static_assert(offsetof(CS2::soundsystem_voicecontainers::CVoiceContainerBlender, m_firstSound) == 0xB8, "m_firstSound in CVoiceContainerBlender should be at offset 0xB8");
		static_assert(offsetof(CS2::soundsystem_voicecontainers::CVoiceContainerBlender, m_secondSound) == 0xD0, "m_secondSound in CVoiceContainerBlender should be at offset 0xD0");
		static_assert(offsetof(CS2::soundsystem_voicecontainers::CVoiceContainerBlender, m_flBlendFactor) == 0xE8, "m_flBlendFactor in CVoiceContainerBlender should be at offset 0xE8");
		static_assert(sizeof(CS2::soundsystem_voicecontainers::CVoiceContainerBlender) == 0xF0, "CVoiceContainerBlender size should be 0xF0");
	}
}
