// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace soundsystem_voicecontainers {
		enum EMode_t : std::uint32_t {
			EMode_t_Peak = 0x0,
			EMode_t_RMS = 0x1
		};
	}
}