// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace materialsystem2 {
		enum HorizJustification_e : std::uint32_t {
			HorizJustification_e_HORIZ_JUSTIFICATION_CENTER = 0x1,
			HorizJustification_e_HORIZ_JUSTIFICATION_LEFT = 0x0,
			HorizJustification_e_HORIZ_JUSTIFICATION_NONE = 0x3,
			HorizJustification_e_HORIZ_JUSTIFICATION_RIGHT = 0x2
		};
	}
}