// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace mathlib_extended {
			// Class size: 0x20
			namespace FunctionInfo_t /**/ {
				constexpr std::ptrdiff_t m_name = 0x8; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nameToken = 0x10; // GlobalTypes::CUtlStringToken  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_nParamCount = 0x14; // int32_t m_nParamCount; |  0x14 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nIndex = 0x18; // mathlib_extended::FuseFunctionIndex_t  | Schema_DeclaredClass | Size: 0x2
				constexpr std::ptrdiff_t m_bIsPure = 0x1a; // bool m_bIsPure; |  0x1a | Schema_Builtin | Size: 0x1
			}
		}
	}
}
