// generated - do not edit!
enum panorama_content_EStyleNodeType {
	COMPILER_CONDITIONAL = 0x10,
	DEFINE = 0x3,
	EXPRESSION = 0x1,
	EXPRESSION_CONCAT = 0xb,
	EXPRESSION_TEXT = 0x9,
	EXPRESSION_URL = 0xa,
	IMPORT = 0x4,
	KEYFRAMES = 0x5,
	KEYFRAME_SELECTOR = 0x6,
	PROPERTY = 0x2,
	REFERENCE_COMPILED = 0xd,
	REFERENCE_CONTENT = 0xc,
	REFERENCE_PANEL = 0xf,
	REFERENCE_PASSTHROUGH = 0xe,
	ROOT = 0x0,
	STYLE_SELECTOR = 0x7,
	WHITESPACE = 0x8
}