// generated - do not edit!
enum modellib_ModelMeshBufferUsage_t {
	MESH_BUFFER_USAGE_ADJACENCY = 0x4,
	MESH_BUFFER_USAGE_IB = 0x2,
	MESH_BUFFER_USAGE_MESHLET_TRIS = 0x8,
	MESH_BUFFER_USAGE_NONE = 0x0,
	MESH_BUFFER_USAGE_RT_PROXY = 0x10,
	MESH_BUFFER_USAGE_VB = 0x1,
	MESH_BUFFER_USAGE_VERTEX_ALBEDO = 0x20
}