// generated - do not edit!
enum modellib_MorphFlexControllerRemapType_t {
	MORPH_FLEXCONTROLLER_REMAP_2WAY = 0x1,
	MORPH_FLEXCONTROLLER_REMAP_EYELID = 0x3,
	MORPH_FLEXCONTROLLER_REMAP_NWAY = 0x2,
	MORPH_FLEXCONTROLLER_REMAP_PASSTHRU = 0x0
}