// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particles/CParticleFunctionInitializer.hpp>
#include <SDK/particleslib/CParticleCollectionVecInput.hpp>
#include <SDK/particles/ParticleAttributeIndex_t.hpp>



namespace CS2 {
	namespace particles {
		class C_INIT_InitVecCollection : public CS2::particles::CParticleFunctionInitializer {
		public:
			particleslib::CParticleCollectionVecInput m_InputValue; // 0x1d8 | Schema_DeclaredClass | Size: 0x6b8
			particles::ParticleAttributeIndex_t m_nOutputField; // 0x890 | Schema_DeclaredClass | Size: 0x4
			S2_PAD(0x4); // End padding
		};
		static_assert(offsetof(CS2::particles::C_INIT_InitVecCollection, m_InputValue) == 0x1D8, "m_InputValue in C_INIT_InitVecCollection should be at offset 0x1D8");
		static_assert(offsetof(CS2::particles::C_INIT_InitVecCollection, m_nOutputField) == 0x890, "m_nOutputField in C_INIT_InitVecCollection should be at offset 0x890");
		static_assert(sizeof(CS2::particles::C_INIT_InitVecCollection) == 0x898, "C_INIT_InitVecCollection size should be 0x898");
	}
}
