// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace modellib {
			// Class size: 0x1
			namespace AttachmentHandle_t /**/ {
				constexpr std::ptrdiff_t m_Value = 0x0; // uint8_t m_Value; |  0x0 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
