// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace modellib {
			// Class size: 0xE8
			namespace CModelConfigElement_AttachedModel /*: public CS2::modellib::CModelConfigElement*/ {
				constexpr std::ptrdiff_t m_InstanceName = 0x48; // GlobalTypes::CUtlString m_InstanceName; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_EntityClass = 0x50; // GlobalTypes::CUtlString m_EntityClass; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_hModel = 0x58; // GlobalTypes::CStrongHandle< resourcesystem::InfoForResourceTypeCModel > m_hModel; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_vOffset = 0x60; // GlobalTypes::Vector m_vOffset; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_aAngOffset = 0x6c; // GlobalTypes::QAngle m_aAngOffset; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_AttachmentName = 0x78; // GlobalTypes::CUtlString m_AttachmentName; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_LocalAttachmentOffsetName = 0x80; // GlobalTypes::CUtlString m_LocalAttachmentOffsetName; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_AttachmentType = 0x88; // modellib::ModelConfigAttachmentType_t m_AttachmentType; |  Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bBoneMergeFlex = 0x8c; // bool m_bBoneMergeFlex; |  0x8c | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bUserSpecifiedColor = 0x8d; // bool m_bUserSpecifiedColor; |  0x8d | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bUserSpecifiedMaterialGroup = 0x8e; // bool m_bUserSpecifiedMaterialGroup; |  0x8e | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bAcceptParentMaterialDrivenDecals = 0x8f; // bool m_bAcceptParentMaterialDrivenDecals; |  0x8f | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_BodygroupOnOtherModels = 0x90; // GlobalTypes::CUtlString m_BodygroupOnOtherModels; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_MaterialGroupOnOtherModels = 0x98; // GlobalTypes::CUtlString m_MaterialGroupOnOtherModels; |  Schema_Atomic | Size: 0x8
			}
		}
	}
}
