// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace modellib {
			// Class size: 0x10
			namespace PermModelDataAnimatedMaterialAttribute_t /**/ {
				constexpr std::ptrdiff_t m_AttributeName = 0x0; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nNumChannels = 0x8; // int32_t m_nNumChannels; |  0x8 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
