#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class CEntityIdentity;
class CScriptComponent;
class CBodyComponent;
class CGameSceneNode;
class CRenderComponent;
class CCollisionProperty;
#include "CNetworkTransmitComponent.hpp"
#include "GameTick_t.hpp"
#include "GameTime_t.hpp"
#include "GameTick_t.hpp"
#include "CNetworkVelocityVector.hpp"
#include "CNetworkVelocityVector.hpp"
#include "GameTime_t.hpp"
#include "CParticleProperty.hpp"

class C_SoundOpvarSetAABBEntity {
    char _vtable_pad_160[0x8];
    CUtlSymbolLarge m_iszPrivateVScripts;
    CEntityIdentity* m_pEntity;
    char pad_161[0x18];
    CScriptComponent* m_CScriptComponent;
    CBodyComponent* m_CBodyComponent;
    CNetworkTransmitComponent m_NetworkTransmitComponent;
    char pad_142[0x120];
    GameTick_t m_nLastThinkTick;
    char pad_143[0x4];
    CGameSceneNode* m_pGameSceneNode;
    CRenderComponent* m_pRenderComponent;
    CCollisionProperty* m_pCollision;
    int32_t m_iMaxHealth;
    int32_t m_iHealth;
    float32 m_flDamageAccumulator;
    uint8_t m_lifeState;
    bool m_bTakesDamage;
    char pad_144[0x2];
    TakeDamageFlags_t m_nTakeDamageFlags;
    EntityPlatformTypes_t m_nPlatformType;
    uint8_t m_ubInterpolationFrame;
    char pad_145[0x2];
    char m_hSceneObjectController[0x4];
    int32_t m_nNoInterpolationTick;
    int32_t m_nVisibilityNoInterpolationTick;
    float32 m_flProxyRandomValue;
    int32_t m_iEFlags;
    uint8_t m_nWaterType;
    bool m_bInterpolateEvenWithNoModel;
    bool m_bPredictionEligible;
    bool m_bApplyLayerMatchIDToModel;
    CUtlStringToken m_tokLayerMatchID;
    CUtlStringToken m_nSubclassID;
    char pad_146[0xc];
    int32_t m_nSimulationTick;
    int32_t m_iCurrentThinkContext;
    char m_aThinkFunctions[0x18];
    bool m_bDisabledContextThinks;
    char pad_147[0x3];
    float32 m_flAnimTime;
    float32 m_flSimulationTime;
    uint8_t m_nSceneObjectOverrideFlags;
    bool m_bHasSuccessfullyInterpolated;
    bool m_bHasAddedVarsToInterpolation;
    bool m_bRenderEvenWhenNotSuccessfullyInterpolated;
    int32_t m_nInterpolationLatchDirtyFlags[2];
    uint16_t m_ListEntry[11];
    char pad_148[0x2];
    GameTime_t m_flCreateTime;
    float32 m_flSpeed;
    uint16_t m_EntClientFlags;
    bool m_bClientSideRagdoll;
    uint8_t m_iTeamNum;
    uint32_t m_spawnflags;
    GameTick_t m_nNextThinkTick;
    char pad_149[0x4];
    uint32_t m_fFlags;
    Vector m_vecAbsVelocity;
    CNetworkVelocityVector m_vecServerVelocity;
    CNetworkVelocityVector m_vecVelocity;
    char pad_150[0xb8];
    Vector m_vecBaseVelocity;
    char m_hEffectEntity[0x4];
    char m_hOwnerEntity[0x4];
    MoveCollide_t m_MoveCollide;
    MoveType_t m_MoveType;
    MoveType_t m_nActualMoveType;
    char pad_151[0x1];
    float32 m_flWaterLevel;
    uint32_t m_fEffects;
    char m_hGroundEntity[0x4];
    int32_t m_nGroundBodyIndex;
    float32 m_flFriction;
    float32 m_flElasticity;
    float32 m_flGravityScale;
    float32 m_flTimeScale;
    bool m_bAnimatedEveryTick;
    bool m_bGravityDisabled;
    char pad_152[0x2];
    GameTime_t m_flNavIgnoreUntilTime;
    uint16_t m_hThink;
    char pad_153[0xe];
    uint8_t m_fBBoxVisFlags;
    char pad_154[0x3];
    float32 m_flActualGravityScale;
    bool m_bGravityActuallyDisabled;
    bool m_bPredictable;
    bool m_bRenderWithViewModels;
    char pad_155[0x1];
    int32_t m_nFirstPredictableCommand;
    int32_t m_nLastPredictableCommand;
    char m_hOldMoveParent[0x4];
    CParticleProperty m_Particles;
    char pad_156[0x8];
    QAngle m_vecAngVelocity;
    int32_t m_DataChangeEventRef;
    char m_dependencies[0x18];
    int32_t m_nCreationTick;
    char pad_157[0x9];
    bool m_bAnimTimeChanged;
    bool m_bSimulationTimeChanged;
    char pad_158[0x9];
    CUtlString m_sUniqueHammerID;
    BloodType m_nBloodType;
    char end_pad_159[0x4];
    CUtlSymbolLarge m_iszStackName;
    CUtlSymbolLarge m_iszOperatorName;
    CUtlSymbolLarge m_iszOpvarName;
    int32_t m_iOpvarIndex;
    bool m_bUseAutoCompare;
    char end_pad_1029[0x3];
};
