#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class CEntityIdentity;
class CScriptComponent;
class CBodyComponent;
class CGameSceneNode;
class CRenderComponent;
class CCollisionProperty;
class CDestructiblePartsComponent;
class CClientAlphaProperty;
class CBaseAnimGraph;
#include "CNetworkTransmitComponent.hpp"
#include "GameTick_t.hpp"
#include "GameTime_t.hpp"
#include "GameTick_t.hpp"
#include "CNetworkVelocityVector.hpp"
#include "CNetworkVelocityVector.hpp"
#include "GameTime_t.hpp"
#include "CParticleProperty.hpp"
#include "CHitboxComponent.hpp"
#include "CCollisionProperty.hpp"
#include "CGlowProperty.hpp"
#include "CNetworkViewOffsetVector.hpp"
#include "PhysicsRagdollPose_t.hpp"
#include "SceneEventId_t.hpp"
#include "AttachmentHandle_t.hpp"
#include "AttachmentHandle_t.hpp"
#include "Emphasized_Phoneme.hpp"
#include "C_AttributeContainer.hpp"
#include "GameTick_t.hpp"
#include "GameTick_t.hpp"
#include "GameTime_t.hpp"
#include "GameTime_t.hpp"
#include "CEntityIOOutput.hpp"
#include "GameTime_t.hpp"
#include "GameTime_t.hpp"
#include "GameTick_t.hpp"
#include "GameTime_t.hpp"
#include "GameTime_t.hpp"
#include "GameTime_t.hpp"
#include "GameTick_t.hpp"
#include "GameTime_t.hpp"
#include "C_IronSightController.hpp"
#include "GameTime_t.hpp"
#include "GameTime_t.hpp"

class C_WeaponSG556 {
    char _vtable_pad_160[0x8];
    CUtlSymbolLarge m_iszPrivateVScripts;
    CEntityIdentity* m_pEntity;
    char pad_161[0x18];
    CScriptComponent* m_CScriptComponent;
    CBodyComponent* m_CBodyComponent;
    CNetworkTransmitComponent m_NetworkTransmitComponent;
    char pad_142[0x120];
    GameTick_t m_nLastThinkTick;
    char pad_143[0x4];
    CGameSceneNode* m_pGameSceneNode;
    CRenderComponent* m_pRenderComponent;
    CCollisionProperty* m_pCollision;
    int32_t m_iMaxHealth;
    int32_t m_iHealth;
    float32 m_flDamageAccumulator;
    uint8_t m_lifeState;
    bool m_bTakesDamage;
    char pad_144[0x2];
    TakeDamageFlags_t m_nTakeDamageFlags;
    EntityPlatformTypes_t m_nPlatformType;
    uint8_t m_ubInterpolationFrame;
    char pad_145[0x2];
    char m_hSceneObjectController[0x4];
    int32_t m_nNoInterpolationTick;
    int32_t m_nVisibilityNoInterpolationTick;
    float32 m_flProxyRandomValue;
    int32_t m_iEFlags;
    uint8_t m_nWaterType;
    bool m_bInterpolateEvenWithNoModel;
    bool m_bPredictionEligible;
    bool m_bApplyLayerMatchIDToModel;
    CUtlStringToken m_tokLayerMatchID;
    CUtlStringToken m_nSubclassID;
    char pad_146[0xc];
    int32_t m_nSimulationTick;
    int32_t m_iCurrentThinkContext;
    char m_aThinkFunctions[0x18];
    bool m_bDisabledContextThinks;
    char pad_147[0x3];
    float32 m_flAnimTime;
    float32 m_flSimulationTime;
    uint8_t m_nSceneObjectOverrideFlags;
    bool m_bHasSuccessfullyInterpolated;
    bool m_bHasAddedVarsToInterpolation;
    bool m_bRenderEvenWhenNotSuccessfullyInterpolated;
    int32_t m_nInterpolationLatchDirtyFlags[2];
    uint16_t m_ListEntry[11];
    char pad_148[0x2];
    GameTime_t m_flCreateTime;
    float32 m_flSpeed;
    uint16_t m_EntClientFlags;
    bool m_bClientSideRagdoll;
    uint8_t m_iTeamNum;
    uint32_t m_spawnflags;
    GameTick_t m_nNextThinkTick;
    char pad_149[0x4];
    uint32_t m_fFlags;
    Vector m_vecAbsVelocity;
    CNetworkVelocityVector m_vecServerVelocity;
    CNetworkVelocityVector m_vecVelocity;
    char pad_150[0xb8];
    Vector m_vecBaseVelocity;
    char m_hEffectEntity[0x4];
    char m_hOwnerEntity[0x4];
    MoveCollide_t m_MoveCollide;
    MoveType_t m_MoveType;
    MoveType_t m_nActualMoveType;
    char pad_151[0x1];
    float32 m_flWaterLevel;
    uint32_t m_fEffects;
    char m_hGroundEntity[0x4];
    int32_t m_nGroundBodyIndex;
    float32 m_flFriction;
    float32 m_flElasticity;
    float32 m_flGravityScale;
    float32 m_flTimeScale;
    bool m_bAnimatedEveryTick;
    bool m_bGravityDisabled;
    char pad_152[0x2];
    GameTime_t m_flNavIgnoreUntilTime;
    uint16_t m_hThink;
    char pad_153[0xe];
    uint8_t m_fBBoxVisFlags;
    char pad_154[0x3];
    float32 m_flActualGravityScale;
    bool m_bGravityActuallyDisabled;
    bool m_bPredictable;
    bool m_bRenderWithViewModels;
    char pad_155[0x1];
    int32_t m_nFirstPredictableCommand;
    int32_t m_nLastPredictableCommand;
    char m_hOldMoveParent[0x4];
    CParticleProperty m_Particles;
    char pad_156[0x8];
    QAngle m_vecAngVelocity;
    int32_t m_DataChangeEventRef;
    char m_dependencies[0x18];
    int32_t m_nCreationTick;
    char pad_157[0x9];
    bool m_bAnimTimeChanged;
    bool m_bSimulationTimeChanged;
    char pad_158[0x9];
    CUtlString m_sUniqueHammerID;
    BloodType m_nBloodType;
    char end_pad_159[0x4];
    char _vtable_pad_36[0x4e8];
    CRenderComponent* m_CRenderComponent;
    CHitboxComponent m_CHitboxComponent;
    CDestructiblePartsComponent* m_pDestructiblePartsSystemComponent;
    HitGroup_t m_LastHitGroup;
    char pad_37[0x4];
    CGlobalSymbol m_sLastDamageSourceName;
    VectorWS m_vLastDamagePosition;
    char pad_38[0x1c];
    bool m_bInitModelEffects;
    bool m_bIsStaticProp;
    char pad_39[0x2];
    int32_t m_nLastAddDecal;
    int32_t m_nDecalsAdded;
    int32_t m_iOldHealth;
    RenderMode_t m_nRenderMode;
    RenderFx_t m_nRenderFX;
    bool m_bAllowFadeInView;
    char pad_40[0x1d];
    Color m_clrRender;
    char pad_41[0x4];
    char m_vecRenderAttributes[0x68];
    char pad_42[0x18];
    bool m_bRenderToCubemaps;
    bool m_bNoInterpolate;
    char pad_43[0x6];
    CCollisionProperty m_Collision;
    CGlowProperty m_Glow;
    float32 m_flGlowBackfaceMult;
    float32 m_fadeMinDist;
    float32 m_fadeMaxDist;
    float32 m_flFadeScale;
    float32 m_flShadowStrength;
    uint8_t m_nObjectCulling;
    char pad_44[0x3];
    int32_t m_nAddDecal;
    Vector m_vDecalPosition;
    Vector m_vDecalForwardAxis;
    DecalMode_t m_nDecalMode;
    DecalMode_t m_nRequiredDecalMode;
    char pad_45[0x2];
    char m_ConfigEntitiesToPropagateMaterialDecalsTo[0x18];
    char pad_46[0x28];
    CNetworkViewOffsetVector m_vecViewOffset;
    char pad_47[0xb8];
    CClientAlphaProperty* m_pClientAlphaProperty;
    Color m_ClientOverrideTint;
    bool m_bUseClientOverrideTint;
    char pad_48[0x3b];
    uint32_t m_bvDisabledHitGroups[1];
    char end_pad_49[0x4];
    char _vtable_pad_28[0x80];
    bool m_bInitiallyPopulateInterpHistory;
    char pad_29[0x1];
    bool m_bSuppressAnimEventSounds;
    char pad_30[0xd];
    bool m_bAnimGraphUpdateEnabled;
    char pad_31[0x3];
    float32 m_flMaxSlopeDistance;
    VectorWS m_vLastSlopeCheckPos;
    bool m_bAnimationUpdateScheduled;
    char pad_32[0x3];
    Vector m_vecForce;
    int32_t m_nForceBone;
    CBaseAnimGraph* m_pClientsideRagdoll;
    bool m_bBuiltRagdoll;
    char pad_33[0x17];
    PhysicsRagdollPose_t m_RagdollPose;
    bool m_bRagdollEnabled;
    bool m_bRagdollClientSide;
    char pad_34[0xe];
    bool m_bHasAnimatedMaterialAttributes;
    char end_pad_35[0x177];
    char _vtable_pad_591[0x10];
    char m_flexWeight[0x18];
    VectorWS m_vLookTargetPosition;
    char pad_592[0x84];
    bool m_blinktoggle;
    char pad_593[0x5f];
    int32_t m_nLastFlexUpdateFrameCount;
    Vector m_CachedViewTarget;
    SceneEventId_t m_nNextSceneEventId;
    int32_t m_iBlink;
    float32 m_blinktime;
    bool m_prevblinktoggle;
    char pad_594[0x3];
    int32_t m_iJawOpen;
    float32 m_flJawOpenAmount;
    float32 m_flBlinkAmount;
    AttachmentHandle_t m_iMouthAttachment;
    AttachmentHandle_t m_iEyeAttachment;
    bool m_bResetFlexWeightsOnModelChange;
    char pad_595[0x19];
    int32_t m_nEyeOcclusionRendererBone;
    matrix3x4_t m_mEyeOcclusionRendererCameraToBoneTransform;
    Vector m_vEyeOcclusionRendererHalfExtent;
    char pad_596[0x10];
    Emphasized_Phoneme m_PhonemeClasses[3];
    char _vtable_pad_583[0x10];
    float32 m_flFlexDelayTime;
    char pad_584[0x4];
    float32* m_flFlexDelayedWeight;
    bool m_bAttributesInitialized;
    char pad_585[0x7];
    C_AttributeContainer m_AttributeManager;
    uint32_t m_OriginalOwnerXuidLow;
    uint32_t m_OriginalOwnerXuidHigh;
    int32_t m_nFallbackPaintKit;
    int32_t m_nFallbackSeed;
    float32 m_flFallbackWear;
    int32_t m_nFallbackStatTrak;
    bool m_bClientside;
    bool m_bParticleSystemsCreated;
    char pad_586[0x6];
    char m_vecAttachedParticles[0x18];
    char m_hViewmodelAttachment[0x4];
    int32_t m_iOldTeam;
    bool m_bAttachmentDirty;
    char pad_587[0x3];
    int32_t m_nUnloadedModelIndex;
    int32_t m_iNumOwnerValidationRetries;
    char pad_588[0xc];
    char m_hOldProvidee[0x4];
    char pad_589[0x4];
    char m_vecAttachedModels[0x18];
    GameTick_t m_nNextPrimaryAttackTick;
    float32 m_flNextPrimaryAttackTickRatio;
    GameTick_t m_nNextSecondaryAttackTick;
    float32 m_flNextSecondaryAttackTickRatio;
    int32_t m_iClip1;
    int32_t m_iClip2;
    int32_t m_pReserveAmmo[2];
    char end_pad_582[0x18];
    char _vtable_pad_560[0x58];
    WeaponGameplayAnimState m_iWeaponGameplayAnimState;
    char pad_561[0x2];
    GameTime_t m_flWeaponGameplayAnimStateTimestamp;
    GameTime_t m_flInspectCancelCompleteTime;
    bool m_bInspectPending;
    bool m_bInspectShouldLoop;
    char pad_562[0x2a];
    float32 m_flCrosshairDistance;
    int32_t m_iAmmoLastCheck;
    int32_t m_nLastEmptySoundCmdNum;
    bool m_bFireOnEmpty;
    char pad_563[0x3];
    CEntityIOOutput m_OnPlayerPickup;
    CSWeaponMode m_weaponMode;
    float32 m_flTurningInaccuracyDelta;
    Vector m_vecTurningInaccuracyEyeDirLast;
    float32 m_flTurningInaccuracy;
    float32 m_fAccuracyPenalty;
    GameTime_t m_flLastAccuracyUpdateTime;
    float32 m_fAccuracySmoothedForZoom;
    int32_t m_iRecoilIndex;
    float32 m_flRecoilIndex;
    bool m_bBurstMode;
    char pad_564[0x3];
    GameTime_t m_flLastBurstModeChangeTime;
    GameTick_t m_nPostponeFireReadyTicks;
    float32 m_flPostponeFireReadyFrac;
    bool m_bInReload;
    char pad_565[0x3];
    GameTime_t m_flDroppedAtTime;
    bool m_bIsHauledBack;
    bool m_bSilencerOn;
    char pad_566[0x2];
    GameTime_t m_flTimeSilencerSwitchComplete;
    int32_t m_iOriginalTeamNumber;
    int32_t m_iMostRecentTeamNumber;
    bool m_bDroppedNearBuyZone;
    char pad_567[0x3];
    float32 m_flNextAttackRenderTimeOffset;
    char pad_568[0x9c];
    bool m_bClearWeaponIdentifyingUGC;
    bool m_bVisualsDataSet;
    bool m_bUIWeapon;
    char pad_569[0x1];
    int32_t m_nCustomEconReloadEventId;
    char pad_570[0x8];
    GameTime_t m_nextPrevOwnerUseTime;
    char m_hPrevOwner[0x4];
    GameTick_t m_nDropTick;
    bool m_bWasActiveWeaponWhenDropped;
    char pad_571[0x1f];
    bool m_donated;
    char pad_572[0x3];
    GameTime_t m_fLastShotTime;
    bool m_bWasOwnedByCT;
    bool m_bWasOwnedByTerrorist;
    char pad_573[0x2];
    float32 m_flNextClientFireBulletTime;
    float32 m_flNextClientFireBulletTime_Repredict;
    char pad_574[0x168];
    C_IronSightController m_IronSightController;
    int32_t m_iIronSightMode;
    char pad_575[0x14];
    GameTime_t m_flLastLOSTraceFailureTime;
    char pad_576[0x5c];
    float32 m_flWatTickOffset;
    char pad_577[0x10];
    GameTime_t m_flLastShakeTime;
    char end_pad_578[0x1b0];
    int32_t m_zoomLevel;
    int32_t m_iBurstShotsRemaining;
    int32_t m_iSilencerBodygroup;
    char pad_557[0xc];
    int32_t m_silencedModelIndex;
    bool m_inPrecache;
    bool m_bNeedsBoltAction;
    char pad_558[0x2];
    int32_t m_nRevolverCylinderIdx;
    char end_pad_559[0xc];
};
