#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

#include "CNetworkVarChainer.hpp"
#include "GameTick_t.hpp"
#include "C_fogplayerparams_t.hpp"
#include "audioparams_t.hpp"
#include "fogparams_t.hpp"
#include "GameTime_t.hpp"

class CCSPlayer_CameraServices {
    char _vtable_pad_635[0x8];
    CNetworkVarChainer __m_pChainEntity;
    char pad_636[0x10];
    QAngle m_vecCsViewPunchAngle;
    GameTick_t m_nCsViewPunchAngleTick;
    float32 m_flCsViewPunchAngleTickRatio;
    char pad_245[0x4];
    C_fogplayerparams_t m_PlayerFog;
    char m_hColorCorrectionCtrl[0x4];
    char m_hViewEntity[0x4];
    char m_hTonemapController[0x4];
    char pad_246[0x4];
    audioparams_t m_audio;
    char m_PostProcessingVolumes[0x18];
    float32 m_flOldPlayerZ;
    float32 m_flOldPlayerViewOffsetZ;
    fogparams_t m_CurrentFog;
    char m_hOldFogController[0x4];
    bool m_bOverrideFogColor[5];
    Color m_OverrideFogColor[5];
    bool m_bOverrideFogStartEnd[5];
    char pad_247[0x2];
    float32 m_fOverrideFogStart[5];
    float32 m_fOverrideFogEnd[5];
    char m_hActivePostProcessingVolume[0x4];
    QAngle m_angDemoViewAngles;
    char end_pad_248[0x84];
    uint32_t m_iFOV;
    uint32_t m_iFOVStart;
    GameTime_t m_flFOVTime;
    float32 m_flFOVRate;
    char m_hZoomOwner[0x4];
    float32 m_flLastShotFOV;
    float32 m_flDeathCamTilt;
    char pad_299[0x4];
    Vector m_vClientScopeInaccuracy;
    char end_pad_300[0x84];
};
