#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

#include "AmmoIndex_t.hpp"
#include "AmmoIndex_t.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeFloat.hpp"
#include "CFiringModeInt.hpp"

class CCSWeaponBaseVData {
    char pad_196[0x28];
    char m_szWorldModel[0xe0];
    char m_sToolsOnlyOwnerModelName[0xe0];
    bool m_bBuiltRightHanded;
    bool m_bAllowFlipping;
    char pad_197[0x6];
    CAttachmentNameSymbolWithStorage m_sMuzzleAttachment;
    char m_szMuzzleFlashParticle[0xe0];
    CUtlString m_szMuzzleFlashParticleConfig;
    char m_szBarrelSmokeParticle[0xe0];
    uint8_t m_nMuzzleSmokeShotThreshold;
    char pad_198[0x3];
    float32 m_flMuzzleSmokeTimeout;
    float32 m_flMuzzleSmokeDecrementRate;
    bool m_bLinkedCooldowns;
    ItemFlagTypes_t m_iFlags;
    AmmoIndex_t m_nPrimaryAmmoType;
    AmmoIndex_t m_nSecondaryAmmoType;
    int32_t m_iMaxClip1;
    int32_t m_iMaxClip2;
    int32_t m_iDefaultClip1;
    int32_t m_iDefaultClip2;
    bool m_bReserveAmmoAsClips;
    bool m_bTreatAsSingleClip;
    bool m_bKeepLoadedAmmo;
    char pad_199[0x1];
    int32_t m_iWeight;
    bool m_bAutoSwitchTo;
    bool m_bAutoSwitchFrom;
    char pad_200[0x2];
    RumbleEffect_t m_iRumbleEffect;
    float32 m_flDropSpeed;
    int32_t m_iSlot;
    int32_t m_iPosition;
    char pad_201[0x4];
    char m_aShootSounds[0x28];
    CSWeaponType m_WeaponType;
    CSWeaponCategory m_WeaponCategory;
    char m_szModel_AG2[0xe0];
    char m_szAnimSkeleton[0xe0];
    Vector m_vecMuzzlePos0;
    Vector m_vecMuzzlePos1;
    char m_szTracerParticle[0xe0];
    gear_slot_t m_GearSlot;
    int32_t m_GearSlotPosition;
    loadout_slot_t m_DefaultLoadoutSlot;
    int32_t m_nPrice;
    int32_t m_nKillAward;
    int32_t m_nPrimaryReserveAmmoMax;
    int32_t m_nSecondaryReserveAmmoMax;
    bool m_bMeleeWeapon;
    bool m_bHasBurstMode;
    bool m_bIsRevolver;
    bool m_bCannotShootUnderwater;
    CGlobalSymbol m_szName;
    CSWeaponSilencerType m_eSilencerType;
    int32_t m_nCrosshairMinDistance;
    int32_t m_nCrosshairDeltaDistance;
    bool m_bIsFullAuto;
    char pad_321[0x3];
    int32_t m_nNumBullets;
    bool m_bReloadsSingleShells;
    char pad_322[0x3];
    CFiringModeFloat m_flCycleTime;
    CFiringModeFloat m_flMaxSpeed;
    CFiringModeFloat m_flSpread;
    CFiringModeFloat m_flInaccuracyCrouch;
    CFiringModeFloat m_flInaccuracyStand;
    CFiringModeFloat m_flInaccuracyJump;
    CFiringModeFloat m_flInaccuracyLand;
    CFiringModeFloat m_flInaccuracyLadder;
    CFiringModeFloat m_flInaccuracyFire;
    CFiringModeFloat m_flInaccuracyMove;
    CFiringModeFloat m_flRecoilAngle;
    CFiringModeFloat m_flRecoilAngleVariance;
    CFiringModeFloat m_flRecoilMagnitude;
    CFiringModeFloat m_flRecoilMagnitudeVariance;
    CFiringModeInt m_nTracerFrequency;
    float32 m_flInaccuracyJumpInitial;
    float32 m_flInaccuracyJumpApex;
    float32 m_flInaccuracyReload;
    float32 m_flDeployDuration;
    float32 m_flDisallowAttackAfterReloadStartDuration;
    int32_t m_nBurstShotCount;
    bool m_bAllowBurstHolster;
    char pad_323[0x3];
    int32_t m_nRecoilSeed;
    int32_t m_nSpreadSeed;
    float32 m_flAttackMovespeedFactor;
    float32 m_flInaccuracyPitchShift;
    float32 m_flInaccuracyAltSoundThreshold;
    CUtlString m_szUseRadioSubtitle;
    bool m_bUnzoomsAfterShot;
    bool m_bHideViewModelWhenZoomed;
    char pad_324[0x2];
    int32_t m_nZoomLevels;
    int32_t m_nZoomFOV1;
    int32_t m_nZoomFOV2;
    float32 m_flZoomTime0;
    float32 m_flZoomTime1;
    float32 m_flZoomTime2;
    float32 m_flIronSightPullUpSpeed;
    float32 m_flIronSightPutDownSpeed;
    float32 m_flIronSightFOV;
    float32 m_flIronSightPivotForward;
    float32 m_flIronSightLooseness;
    int32_t m_nDamage;
    float32 m_flHeadshotMultiplier;
    float32 m_flArmorRatio;
    float32 m_flPenetration;
    float32 m_flRange;
    float32 m_flRangeModifier;
    float32 m_flFlinchVelocityModifierLarge;
    float32 m_flFlinchVelocityModifierSmall;
    float32 m_flRecoveryTimeCrouch;
    float32 m_flRecoveryTimeStand;
    float32 m_flRecoveryTimeCrouchFinal;
    float32 m_flRecoveryTimeStandFinal;
    int32_t m_nRecoveryTransitionStartBullet;
    int32_t m_nRecoveryTransitionEndBullet;
    float32 m_flThrowVelocity;
    Vector m_vSmokeColor;
    CGlobalSymbol m_szAnimClass;
    char end_pad_325[0x30];
};
