// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropAttributeGridPlacementMode  {
		public:
			S2_PAD(0x40);
		};
#ifdef USE_STATIC_ASSERTS
		static_assert(sizeof(CS2::smartprops::CSmartPropAttributeGridPlacementMode) == 0x40, "CSmartPropAttributeGridPlacementMode size should be 0x40");

#endif
	}
}
