// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropAttributeRadiusPlacementMode  {
		public:
			S2_PAD(0x40);
		};
		static_assert(sizeof(CS2::smartprops::CSmartPropAttributeRadiusPlacementMode) == 0x40, "CSmartPropAttributeRadiusPlacementMode size should be 0x40");
	}
}
