// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/CPulseCell_BaseRequirement.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace smartprops {
		class CSmartPropPulse_SelectionEndCap : public CS2::pulse_runtime_lib::CPulseCell_BaseRequirement {
		public:
		};
		static_assert(sizeof(CS2::smartprops::CSmartPropPulse_SelectionEndCap) == 0x48, "CSmartPropPulse_SelectionEndCap size should be 0x48");
	}
}
