// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace smartprops {
		enum SmartPropColorSelectionMode_t : std::uint32_t {
			SmartPropColorSelectionMode_t_GRADIENT_LOCATION = 0x3,
			SmartPropColorSelectionMode_t_GRADIENT_RANDOM = 0x1,
			SmartPropColorSelectionMode_t_GRADIENT_RANDOM_STOP = 0x2,
			SmartPropColorSelectionMode_t_SPECIFIC_COLOR = 0x0
		};
	}
}