// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class Input_t  {
		public:
			GlobalTypes::Vector m_inputValue; // 0x0 | Schema_Atomic | Size: 0xc
			S2_PAD(0x4);
			GlobalTypes::CUtlVector< float32 > m_outputWeightList; // 0x10 | Schema_Atomic | Size: 0x18
			// char  m_outputWeightList[0x18]; // 0x10 | Schema_Atomic | Size: 0x18
		};
		static_assert(offsetof(CS2::modellib::Input_t, m_inputValue) == 0x0, "m_inputValue in CBoneConstraintPoseSpaceMorph::Input_t should be at offset 0x0");
		static_assert(offsetof(CS2::modellib::Input_t, m_outputWeightList) == 0x10, "m_outputWeightList in CBoneConstraintPoseSpaceMorph::Input_t should be at offset 0x10");
		static_assert(sizeof(CS2::modellib::Input_t) == 0x28, "CBoneConstraintPoseSpaceMorph::Input_t size should be 0x28");
	}
}
