// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace modellib {
		class MaterialGroup_t  {
		public:
			GlobalTypes::CUtlString m_name; // 0x0 | Schema_Atomic | Size: 0x8
			GlobalTypes::CUtlVector< GlobalTypes::CStrongHandle< InfoForResourceTypeIMaterial2 > > m_materials; // 0x8 | Schema_Atomic | Size: 0x18
			// char  m_materials[0x18]; // 0x8 | Schema_Atomic | Size: 0x18
		};
		static_assert(offsetof(CS2::modellib::MaterialGroup_t, m_name) == 0x0, "m_name in MaterialGroup_t should be at offset 0x0");
		static_assert(offsetof(CS2::modellib::MaterialGroup_t, m_materials) == 0x8, "m_materials in MaterialGroup_t should be at offset 0x8");
		static_assert(sizeof(CS2::modellib::MaterialGroup_t) == 0x20, "MaterialGroup_t size should be 0x20");
	}
}
