// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace modellib {
		enum ModelBoneFlexComponent_t : std::uint32_t {
			ModelBoneFlexComponent_t_MODEL_BONE_FLEX_INVALID = 0xffffffff,
			ModelBoneFlexComponent_t_MODEL_BONE_FLEX_TX = 0x0,
			ModelBoneFlexComponent_t_MODEL_BONE_FLEX_TY = 0x1,
			ModelBoneFlexComponent_t_MODEL_BONE_FLEX_TZ = 0x2
		};
	}
}