// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace smartprops {
			// Class size: 0x50
			namespace CSmartPropSelectionCriteria_IsValid /*: public CS2::smartprops::CSmartPropSelectionCriteria*/ {
				constexpr std::ptrdiff_t m_Expression = 0x48; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
			}
		}
	}
}
