// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace smartprops {
			// Class size: 0x190
			namespace CSmartPropOperation_SetOrientation /*: public CS2::smartprops::CSmartPropTransformOperation*/ {
				constexpr std::ptrdiff_t m_vForwardVector = 0x50; // GlobalTypes::CSmartPropAttributeVector  | Schema_Atomic | Size: 0x40
				constexpr std::ptrdiff_t m_ForwardDirectionSpace = 0x90; // smartprops::CSmartPropAttributeCoordinateSpace  | Schema_DeclaredClass | Size: 0x40
				constexpr std::ptrdiff_t m_vUpVector = 0xd0; // GlobalTypes::CSmartPropAttributeVector  | Schema_Atomic | Size: 0x40
				constexpr std::ptrdiff_t m_UpDirectionSpace = 0x110; // smartprops::CSmartPropAttributeCoordinateSpace  | Schema_DeclaredClass | Size: 0x40
				constexpr std::ptrdiff_t m_bPrioritizeUp = 0x150; // GlobalTypes::CSmartPropAttributeBool  | Schema_Atomic | Size: 0x40
			}
		}
	}
}
