// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace smartprops {
			// Class size: 0xD8
			namespace CSmartPropOperation_SaveDirection /*: public CS2::smartprops::CSmartPropOperation*/ {
				constexpr std::ptrdiff_t m_DirectionVector = 0x50; // smartprops::CSmartPropAttributeDirection  | Schema_DeclaredClass | Size: 0x40
				constexpr std::ptrdiff_t m_CoordinateSpace = 0x90; // smartprops::CSmartPropAttributeCoordinateSpace  | Schema_DeclaredClass | Size: 0x40
				constexpr std::ptrdiff_t m_VariableName = 0xd0; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
			}
		}
	}
}
