// generated - do not edit!
enum animationsystem_ParticleAttachment_t {
	MAX_PATTACH_TYPES = 0x10,
	PATTACH_ABSORIGIN = 0x0,
	PATTACH_ABSORIGIN_FOLLOW = 0x1,
	PATTACH_CENTER_FOLLOW = 0xd,
	PATTACH_CUSTOMORIGIN = 0x2,
	PATTACH_CUSTOMORIGIN_FOLLOW = 0x3,
	PATTACH_CUSTOM_GAME_STATE_1 = 0xe,
	PATTACH_EYES_FOLLOW = 0x6,
	PATTACH_HEALTHBAR = 0xf,
	PATTACH_INVALID = 0xffffffff,
	PATTACH_MAIN_VIEW = 0xb,
	PATTACH_OVERHEAD_FOLLOW = 0x7,
	PATTACH_POINT = 0x4,
	PATTACH_POINT_FOLLOW = 0x5,
	PATTACH_RENDERORIGIN_FOLLOW = 0xa,
	PATTACH_ROOTBONE_FOLLOW = 0x9,
	PATTACH_WATERWAKE = 0xc,
	PATTACH_WORLDORIGIN = 0x8
}