// generated - do not edit!
enum client_ChoreoState_t {
	STATE_PLAY_SCRIPT = 0x4,
	STATE_PLAY_SCRIPT_POST_IDLE = 0x5,
	STATE_PLAY_SCRIPT_POST_IDLE_DONE = 0x6,
	STATE_PRE_SCRIPT = 0x0,
	STATE_SYNCHRONIZE_SCRIPT = 0x3,
	STATE_WAIT_FOR_SCRIPT = 0x1,
	STATE_WALK_TO_MARK = 0x2
}