// generated - do not edit!
enum client_Class_T {
	CLASS_C4_FOR_RADAR = 0x3,
	CLASS_DOOR = 0xb,
	CLASS_FOOT_CONTACT_SHADOW = 0x4,
	CLASS_HUDMODEL_ADDON = 0x9,
	CLASS_HUDMODEL_ARMS = 0x8,
	CLASS_HUDMODEL_WEAPON = 0x7,
	CLASS_NONE = 0x0,
	CLASS_PLANTED_C4 = 0xc,
	CLASS_PLAYER = 0x1,
	CLASS_PLAYER_ALLY = 0x2,
	CLASS_WATER_SPLASHER = 0x6,
	CLASS_WEAPON = 0x5,
	CLASS_WORLDMODEL_GLOVES = 0xa,
	NUM_CLASSIFY_CLASSES = 0xd
}