// generated - do not edit!
enum client_CSPlayerState {
	NUM_PLAYER_STATES = 0x9,
	STATE_ACTIVE = 0x0,
	STATE_DEATH_ANIM = 0x4,
	STATE_DEATH_WAIT_FOR_KEY = 0x5,
	STATE_DORMANT = 0x8,
	STATE_GUNGAME_RESPAWN = 0x7,
	STATE_OBSERVER_MODE = 0x6,
	STATE_PICKINGCLASS = 0x3,
	STATE_PICKINGTEAM = 0x2,
	STATE_WELCOME = 0x1
}