// generated - do not edit!
enum client_CSWeaponCategory {
	WEAPONCATEGORY_COUNT = 0x6,
	WEAPONCATEGORY_HEAVY = 0x5,
	WEAPONCATEGORY_MELEE = 0x1,
	WEAPONCATEGORY_OTHER = 0x0,
	WEAPONCATEGORY_RIFLE = 0x4,
	WEAPONCATEGORY_SECONDARY = 0x2,
	WEAPONCATEGORY_SMG = 0x3
}