// generated - do not edit!
enum client_CSWeaponType {
	WEAPONTYPE_C4 = 0x7,
	WEAPONTYPE_EQUIPMENT = 0xa,
	WEAPONTYPE_GRENADE = 0x9,
	WEAPONTYPE_KNIFE = 0x0,
	WEAPONTYPE_MACHINEGUN = 0x6,
	WEAPONTYPE_PISTOL = 0x1,
	WEAPONTYPE_RIFLE = 0x3,
	WEAPONTYPE_SHOTGUN = 0x4,
	WEAPONTYPE_SNIPER_RIFLE = 0x5,
	WEAPONTYPE_STACKABLEITEM = 0xb,
	WEAPONTYPE_SUBMACHINEGUN = 0x2,
	WEAPONTYPE_TASER = 0x8,
	WEAPONTYPE_UNKNOWN = 0xc
}