// generated - do not edit!
enum client_EntityDisolveType_t {
	ENTITY_DISSOLVE_CORE = 0x3,
	ENTITY_DISSOLVE_ELECTRICAL = 0x1,
	ENTITY_DISSOLVE_ELECTRICAL_LIGHT = 0x2,
	ENTITY_DISSOLVE_INVALID = 0xffffffff,
	ENTITY_DISSOLVE_NORMAL = 0x0
}