// generated - do not edit!
enum client_GrenadeType_t {
	GRENADE_TYPE_DECOY = 0x3,
	GRENADE_TYPE_EXPLOSIVE = 0x0,
	GRENADE_TYPE_FIRE = 0x2,
	GRENADE_TYPE_FLASH = 0x1,
	GRENADE_TYPE_SMOKE = 0x4,
	GRENADE_TYPE_TOTAL = 0x5
}