// generated - do not edit!
enum client_HierarchyType_t {
	HIERARCHY_ABSORIGIN = 0x3,
	HIERARCHY_ATTACHMENT = 0x2,
	HIERARCHY_BONE = 0x4,
	HIERARCHY_BONE_MERGE = 0x1,
	HIERARCHY_NONE = 0x0,
	HIERARCHY_TYPE_COUNT = 0x5
}