// generated - do not edit!
enum client_HitGroup_t {
	HITGROUP_CHEST = 0x2,
	HITGROUP_COUNT = 0xc,
	HITGROUP_GEAR = 0xa,
	HITGROUP_GENERIC = 0x0,
	HITGROUP_HEAD = 0x1,
	HITGROUP_INVALID = 0xffffffff,
	HITGROUP_LEFTARM = 0x4,
	HITGROUP_LEFTLEG = 0x6,
	HITGROUP_NECK = 0x8,
	HITGROUP_RIGHTARM = 0x5,
	HITGROUP_RIGHTLEG = 0x7,
	HITGROUP_SPECIAL = 0xb,
	HITGROUP_STOMACH = 0x3,
	HITGROUP_UNUSED = 0x9
}