// generated - do not edit!
enum client_InventoryNodeType_t {
	CONCRETE_NODE_SCHEMA_ITEMDEF = 0x6,
	CONCRETE_NODE_SCHEMA_KEYCHAIN = 0x8,
	CONCRETE_NODE_SCHEMA_PREFAB = 0x5,
	CONCRETE_NODE_SCHEMA_STICKER = 0x7,
	NODE_TYPE_INVALID = 0x0,
	VIRTUAL_NODE_SCHEMA_ITEMDEF = 0x2,
	VIRTUAL_NODE_SCHEMA_KEYCHAIN = 0x4,
	VIRTUAL_NODE_SCHEMA_PREFAB = 0x1,
	VIRTUAL_NODE_SCHEMA_STICKER = 0x3
}