// generated - do not edit!
enum client_MoveCollide_t {
	MOVECOLLIDE_COUNT = 0x4,
	MOVECOLLIDE_DEFAULT = 0x0,
	MOVECOLLIDE_FLY_BOUNCE = 0x1,
	MOVECOLLIDE_FLY_CUSTOM = 0x2,
	MOVECOLLIDE_FLY_SLIDE = 0x3,
	MOVECOLLIDE_MAX_BITS = 0x3
}