// generated - do not edit!
enum client_PointTemplateOwnerSpawnGroupType_t {
	INSERT_INTO_CURRENTLY_ACTIVE_SPAWN_GROUP = 0x1,
	INSERT_INTO_NEWLY_CREATED_SPAWN_GROUP = 0x2,
	INSERT_INTO_POINT_TEMPLATE_SPAWN_GROUP = 0x0
}