// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "CNmBoneMaskValueNode_CDefinition.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmBoneMaskBlendNode_CDefinition : public CS2::animlib::CNmBoneMaskValueNode_CDefinition {
		public:
			int16_t m_nSourceMaskNodeIdx; // 0x10 | Schema_Builtin | Size: 0x2
			int16_t m_nTargetMaskNodeIdx; // 0x12 | Schema_Builtin | Size: 0x2
			int16_t m_nBlendWeightValueNodeIdx; // 0x14 | Schema_Builtin | Size: 0x2
			S2_PAD(0x2); // End padding
		};
		static_assert(offsetof(CS2::animlib::CNmBoneMaskBlendNode_CDefinition, m_nSourceMaskNodeIdx) == 0x10, "m_nSourceMaskNodeIdx in CNmBoneMaskBlendNode::CDefinition should be at offset 0x10");
		static_assert(offsetof(CS2::animlib::CNmBoneMaskBlendNode_CDefinition, m_nTargetMaskNodeIdx) == 0x12, "m_nTargetMaskNodeIdx in CNmBoneMaskBlendNode::CDefinition should be at offset 0x12");
		static_assert(offsetof(CS2::animlib::CNmBoneMaskBlendNode_CDefinition, m_nBlendWeightValueNodeIdx) == 0x14, "m_nBlendWeightValueNodeIdx in CNmBoneMaskBlendNode::CDefinition should be at offset 0x14");
		static_assert(sizeof(CS2::animlib::CNmBoneMaskBlendNode_CDefinition) == 0x18, "CNmBoneMaskBlendNode::CDefinition size should be 0x18");
	}
}
