// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/animlib/CNmPoseTask.hpp>



namespace CS2 {
	namespace animlib {
		class CNmCachedPoseWriteTask : public CS2::animlib::CNmPoseTask {
		public:
			S2_PAD(0x8);
		};
		static_assert(sizeof(CS2::animlib::CNmCachedPoseWriteTask) == 0x58, "CNmCachedPoseWriteTask size should be 0x58");
	}
}
