// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "CNmIDValueNode_CDefinition.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmControlParameterIDNode_CDefinition : public CS2::animlib::CNmIDValueNode_CDefinition {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		static_assert(sizeof(CS2::animlib::CNmControlParameterIDNode_CDefinition) == 0x10, "CNmControlParameterIDNode::CDefinition size should be 0x10");

#endif
	}
}
