// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace animlib {
		enum CNmFloatMathNode_Operator_t : std::uint8_t {
			CNmFloatMathNode_Operator_t_Abs = 0x5,
			CNmFloatMathNode_Operator_t_Add = 0x0,
			CNmFloatMathNode_Operator_t_Ceiling = 0x8,
			CNmFloatMathNode_Operator_t_Div = 0x3,
			CNmFloatMathNode_Operator_t_Floor = 0x7,
			CNmFloatMathNode_Operator_t_FractionalPart = 0xa,
			CNmFloatMathNode_Operator_t_IntegerPart = 0x9,
			CNmFloatMathNode_Operator_t_InverseFractionalPart = 0xb,
			CNmFloatMathNode_Operator_t_Mod = 0x4,
			CNmFloatMathNode_Operator_t_Mul = 0x2,
			CNmFloatMathNode_Operator_t_Negate = 0x6,
			CNmFloatMathNode_Operator_t_Sub = 0x1
		};
	}
}