// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace animlib {
		enum CNmRootMotionOverrideNode_OverrideFlags_t : std::uint8_t {
			CNmRootMotionOverrideNode_OverrideFlags_t_AllowFacingPitch = 0x3,
			CNmRootMotionOverrideNode_OverrideFlags_t_AllowMoveX = 0x0,
			CNmRootMotionOverrideNode_OverrideFlags_t_AllowMoveY = 0x1,
			CNmRootMotionOverrideNode_OverrideFlags_t_AllowMoveZ = 0x2,
			CNmRootMotionOverrideNode_OverrideFlags_t_ListenForEvents = 0x4
		};
	}
}