// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "CNmValueNode_CDefinition.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class CNmTargetValueNode_CDefinition : public CS2::animlib::CNmValueNode_CDefinition {
		public:
		};
		static_assert(sizeof(CS2::animlib::CNmTargetValueNode_CDefinition) == 0x10, "CNmTargetValueNode::CDefinition size should be 0x10");
	}
}
