// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace animlib {
		class NmPercent_t  {
		public:
			float32 m_flValue; // 0x0 | Schema_Builtin | Size: 0x4
		};
		static_assert(offsetof(CS2::animlib::NmPercent_t, m_flValue) == 0x0, "m_flValue in NmPercent_t should be at offset 0x0");
		static_assert(sizeof(CS2::animlib::NmPercent_t) == 0x4, "NmPercent_t size should be 0x4");
	}
}
