// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace animlib {
		enum OverrideFlags_t : std::uint8_t {
			OverrideFlags_t_AllowFacingPitch = 0x3,
			OverrideFlags_t_AllowMoveX = 0x0,
			OverrideFlags_t_AllowMoveY = 0x1,
			OverrideFlags_t_AllowMoveZ = 0x2,
			OverrideFlags_t_ListenForEvents = 0x4
		};
	}
}