// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace animlib {
		class SecondarySkeleton_t  {
		public:
			GlobalTypes::CGlobalSymbol m_attachToBoneID; // 0x0 | Schema_Atomic | Size: 0x8
			// GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCNmSkeleton> m_skeleton; // 0x8 | Schema_Atomic | Size: 0x8
			char  m_skeleton[0x8]; // 0x8 | Schema_Atomic | Size: 0x8
		};
		static_assert(offsetof(CS2::animlib::SecondarySkeleton_t, m_attachToBoneID) == 0x0, "m_attachToBoneID in CNmSkeleton::SecondarySkeleton_t should be at offset 0x0");
		static_assert(offsetof(CS2::animlib::SecondarySkeleton_t, m_skeleton) == 0x8, "m_skeleton in CNmSkeleton::SecondarySkeleton_t should be at offset 0x8");
		static_assert(sizeof(CS2::animlib::SecondarySkeleton_t) == 0x10, "CNmSkeleton::SecondarySkeleton_t size should be 0x10");
	}
}
