// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif







using namespace GlobalTypes;
namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeCAnimationGroup  {
		public:
			S2_PAD(0x1);
		};
		static_assert(sizeof(CS2::resourcesystem::InfoForResourceTypeCAnimationGroup) == 0x1, "InfoForResourceTypeCAnimationGroup size should be 0x1");
	}
}
