// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace resourcesystem {
		class InfoForResourceTypeManifestTestResource_t  {
		public:
			S2_PAD(0x1);
		};
		static_assert(sizeof(CS2::resourcesystem::InfoForResourceTypeManifestTestResource_t) == 0x1, "InfoForResourceTypeManifestTestResource_t size should be 0x1");
	}
}
