// generated - do not edit!
enum particleslib_PFNoiseTurbulence_t {
	PF_NOISE_TURB_ALTERNATE = 0x5,
	PF_NOISE_TURB_CONTRAST = 0x4,
	PF_NOISE_TURB_FEEDBACK = 0x2,
	PF_NOISE_TURB_HIGHLIGHT = 0x1,
	PF_NOISE_TURB_LOOPY = 0x3,
	PF_NOISE_TURB_NONE = 0x0
}