// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animgraphlib {
			// Class size: 0x40
			namespace BlendItem_t /**/ {
				constexpr std::ptrdiff_t m_tags = 0x0; // GlobalTypes::CUtlVector<animgraphlib::TagSpan_t>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_pChild = 0x18; // animgraphlib::CAnimUpdateNodeRef  | Schema_DeclaredClass | Size: 0x10
				constexpr std::ptrdiff_t m_hSequence = 0x28; // animationsystem::HSequence  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_vPos = 0x2c; // GlobalTypes::Vector2D  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_flDuration = 0x34; // float32 m_flDuration; |  0x34 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bUseCustomDuration = 0x38; // bool m_bUseCustomDuration; |  0x38 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
