// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace worldrenderer {
		class EntityKeyValueData_t  {
		public:
			S2_PAD(0x8);
			// GlobalTypes::CUtlVector< worldrenderer::EntityIOConnectionData_t > m_connections; // 0x8 | Schema_Atomic | Size: 0x18
			char  m_connections[0x18]; // 0x8 | Schema_Atomic | Size: 0x18
			GlobalTypes::CUtlBinaryBlock m_keyValuesData; // 0x20 | Schema_Atomic | Size: 0x10
			S2_PAD(0x8); // End padding
		};
		static_assert(offsetof(CS2::worldrenderer::EntityKeyValueData_t, m_connections) == 0x8, "m_connections in EntityKeyValueData_t should be at offset 0x8");
		static_assert(offsetof(CS2::worldrenderer::EntityKeyValueData_t, m_keyValuesData) == 0x20, "m_keyValuesData in EntityKeyValueData_t should be at offset 0x20");
		static_assert(sizeof(CS2::worldrenderer::EntityKeyValueData_t) == 0x38, "EntityKeyValueData_t size should be 0x38");
	}
}
