// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/entity2/CNetworkVarChainer.hpp>



namespace CS2 {
	namespace server {
		class CCSGameModeRules  {
		public:
			S2_PAD(0x8);
			entity2::CNetworkVarChainer __m_pChainEntity; // 0x8 | Schema_DeclaredClass | Size: 0x28
		};
		static_assert(offsetof(CS2::server::CCSGameModeRules, __m_pChainEntity) == 0x8, "__m_pChainEntity in CCSGameModeRules should be at offset 0x8");
		static_assert(sizeof(CS2::server::CCSGameModeRules) == 0x30, "CCSGameModeRules size should be 0x30");
	}
}
