// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CInferno.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CFireCrackerBlast : public CS2::server::CInferno {
		public:
		};
		static_assert(sizeof(CS2::server::CFireCrackerBlast) == 0x13B8, "CFireCrackerBlast size should be 0x13B8");
	}
}
