// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "CBaseEntity.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CGameRulesProxy : public CS2::server::CBaseEntity {
		public:
		};
		static_assert(sizeof(CS2::server::CGameRulesProxy) == 0x4A8, "CGameRulesProxy size should be 0x4A8");
	}
}
