// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "SpawnPoint.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CInfoPlayerTerrorist : public CS2::server::SpawnPoint {
		public:
		};
		static_assert(sizeof(CS2::server::CInfoPlayerTerrorist) == 0x4B8, "CInfoPlayerTerrorist size should be 0x4B8");
	}
}
