// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CItemDefuser.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CItemDefuserAlias_item_defuser : public CS2::server::CItemDefuser {
		public:
		};
		static_assert(sizeof(CS2::server::CItemDefuserAlias_item_defuser) == 0xB90, "CItemDefuserAlias_item_defuser size should be 0xB90");
	}
}
