// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace server {
		class CLogicAchievement : public CS2::server::CLogicalEntity {
		public:
			bool m_bDisabled; // 0x4f0 | Schema_Builtin | Size: 0x1
			S2_PAD(0x7);
			GlobalTypes::CUtlSymbolLarge m_iszAchievementEventID; // 0x4f8 | Schema_Atomic | Size: 0x8
			entity2::CEntityIOOutput m_OnFired; // 0x500 | Schema_DeclaredClass | Size: 0x28
		};
		static_assert(offsetof(CS2::server::CLogicAchievement, m_bDisabled) == 0x4F0, "m_bDisabled in CLogicAchievement should be at offset 0x4F0");
		static_assert(offsetof(CS2::server::CLogicAchievement, m_iszAchievementEventID) == 0x4F8, "m_iszAchievementEventID in CLogicAchievement should be at offset 0x4F8");
		static_assert(offsetof(CS2::server::CLogicAchievement, m_OnFired) == 0x500, "m_OnFired in CLogicAchievement should be at offset 0x500");
		static_assert(sizeof(CS2::server::CLogicAchievement) == 0x528, "CLogicAchievement size should be 0x528");
	}
}
