// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CNavVolumeCalculatedVector.hpp>



namespace CS2 {
	namespace server {
		class CNavVolumeBreadthFirstSearch : public CS2::server::CNavVolumeCalculatedVector {
		public:
			S2_PAD(0x8);
			GlobalTypes::Vector m_vStartPos; // 0xa8 | Schema_Atomic | Size: 0xc
			float32 m_flSearchDist; // 0xb4 | Schema_Builtin | Size: 0x4
			S2_PAD(0x8); // End padding
		};
		static_assert(offsetof(CS2::server::CNavVolumeBreadthFirstSearch, m_vStartPos) == 0xA8, "m_vStartPos in CNavVolumeBreadthFirstSearch should be at offset 0xA8");
		static_assert(offsetof(CS2::server::CNavVolumeBreadthFirstSearch, m_flSearchDist) == 0xB4, "m_flSearchDist in CNavVolumeBreadthFirstSearch should be at offset 0xB4");
		static_assert(sizeof(CS2::server::CNavVolumeBreadthFirstSearch) == 0xC0, "CNavVolumeBreadthFirstSearch size should be 0xC0");
	}
}
