// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/server/CPathParticleRope.hpp>



namespace CS2 {
	namespace server {
		class CPathParticleRopeAlias_path_particle_rope_clientside : public CS2::server::CPathParticleRope {
		public:
		};
		static_assert(sizeof(CS2::server::CPathParticleRopeAlias_path_particle_rope_clientside) == 0x5D8, "CPathParticleRopeAlias_path_particle_rope_clientside size should be 0x5D8");
	}
}
