// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CPointClientUIWorldPanel.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPointClientUIWorldTextPanel : public CS2::server::CPointClientUIWorldPanel {
		public:
			char m_messageText[512]; // 0x9e0 | Schema_FixedArray | Size: 0x200
		};
		static_assert(offsetof(CS2::server::CPointClientUIWorldTextPanel, m_messageText) == 0x9E0, "m_messageText in CPointClientUIWorldTextPanel should be at offset 0x9E0");
		static_assert(sizeof(CS2::server::CPointClientUIWorldTextPanel) == 0xBE0, "CPointClientUIWorldTextPanel size should be 0xBE0");
	}
}
