// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "../pulse_runtime_lib/CPulseCell_BaseLerp_CursorState_t.hpp"
#include "../client/PointCameraSettings_t.hpp"



namespace CS2 {
	namespace server {
		class CPointCamera;
	}
}


using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CPulseCell_LerpCameraSettings_CursorState_t : public CS2::pulse_runtime_lib::CPulseCell_BaseLerp_CursorState_t {
		public:
			GlobalTypes::CHandle<server::CPointCamera> m_hCamera; // 0x8 | Schema_Atomic | Size: 0x4
			// char m_hCamera[0x4]; // 0x8 | Schema_Atomic | Size: 0x4
			client::PointCameraSettings_t m_OverlaidStart; // 0xc | Schema_DeclaredClass | Size: 0x10
			client::PointCameraSettings_t m_OverlaidEnd; // 0x1c | Schema_DeclaredClass | Size: 0x10
		};
		static_assert(offsetof(CS2::server::CPulseCell_LerpCameraSettings_CursorState_t, m_hCamera) == 0x8, "m_hCamera in CPulseCell_LerpCameraSettings::CursorState_t should be at offset 0x8");
		static_assert(offsetof(CS2::server::CPulseCell_LerpCameraSettings_CursorState_t, m_OverlaidStart) == 0xC, "m_OverlaidStart in CPulseCell_LerpCameraSettings::CursorState_t should be at offset 0xC");
		static_assert(offsetof(CS2::server::CPulseCell_LerpCameraSettings_CursorState_t, m_OverlaidEnd) == 0x1C, "m_OverlaidEnd in CPulseCell_LerpCameraSettings::CursorState_t should be at offset 0x1C");
		static_assert(sizeof(CS2::server::CPulseCell_LerpCameraSettings_CursorState_t) == 0x2C, "CPulseCell_LerpCameraSettings::CursorState_t size should be 0x2C");
	}
}
