// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/server/CMultiplayRules.hpp>



namespace CS2 {
	namespace server {
		class CTeamplayRules : public CS2::server::CMultiplayRules {
		public:
		};
		static_assert(sizeof(CS2::server::CTeamplayRules) == 0xC0, "CTeamplayRules size should be 0xC0");
	}
}
