// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/CBaseTrigger.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerRemove : public CS2::server::CBaseTrigger {
		public:
			entity2::CEntityIOOutput m_OnRemove; // 0x890 | Schema_DeclaredClass | Size: 0x18
		};
		static_assert(offsetof(CS2::server::CTriggerRemove, m_OnRemove) == 0x890, "m_OnRemove in CTriggerRemove should be at offset 0x890");
		static_assert(sizeof(CS2::server::CTriggerRemove) == 0x8A8, "CTriggerRemove size should be 0x8A8");
	}
}
