// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "CBaseTrigger.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace server {
		class CTriggerGravity : public CS2::server::CBaseTrigger {
		public:
		};
		static_assert(sizeof(CS2::server::CTriggerGravity) == 0x890, "CTriggerGravity size should be 0x890");
	}
}
