// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/server/CCSWeaponBaseGun.hpp>



namespace CS2 {
	namespace server {
		class CWeaponMag7 : public CS2::server::CCSWeaponBaseGun {
		public:
		};
		static_assert(sizeof(CS2::server::CWeaponMag7) == 0x11C8, "CWeaponMag7 size should be 0x11C8");
	}
}
