// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/server/CCSWeaponBaseGun.hpp>



namespace CS2 {
	namespace server {
		class CWeaponMP5SD : public CS2::server::CCSWeaponBaseGun {
		public:
		};
		static_assert(sizeof(CS2::server::CWeaponMP5SD) == 0x11F0, "CWeaponMP5SD size should be 0x11F0");
	}
}
