// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/server/CCSWeaponBaseGun.hpp>
#include <SDK/entity2/GameTime_t.hpp>



namespace CS2 {
	namespace server {
		class CWeaponTaser : public CS2::server::CCSWeaponBaseGun {
		public:
			entity2::GameTime_t m_fFireTime; // 0x11c8 | Schema_DeclaredClass | Size: 0x4
			int32_t m_nLastAttackTick; // 0x11cc | Schema_Builtin | Size: 0x4
		};
		static_assert(offsetof(CS2::server::CWeaponTaser, m_fFireTime) == 0x11C8, "m_fFireTime in CWeaponTaser should be at offset 0x11C8");
		static_assert(offsetof(CS2::server::CWeaponTaser, m_nLastAttackTick) == 0x11CC, "m_nLastAttackTick in CWeaponTaser should be at offset 0x11CC");
		static_assert(sizeof(CS2::server::CWeaponTaser) == 0x11D0, "CWeaponTaser size should be 0x11D0");
	}
}
