// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/server/CBaseModelEntity.hpp>



namespace CS2 {
	namespace server {
		class CWorld : public CS2::server::CBaseModelEntity {
		public:
		};
		static_assert(sizeof(CS2::server::CWorld) == 0x7F0, "CWorld size should be 0x7F0");
	}
}
