// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace server {
		enum doorCheck_e : std::uint32_t {
			doorCheck_e_DOOR_CHECK_BACKWARD = 0x1,
			doorCheck_e_DOOR_CHECK_FORWARD = 0x0,
			doorCheck_e_DOOR_CHECK_FULL = 0x2
		};
	}
}