// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/server/dynpitchvol_base_t.hpp>



namespace CS2 {
	namespace server {
		class dynpitchvol_t : public CS2::server::dynpitchvol_base_t {
		public:
		};
		static_assert(sizeof(CS2::server::dynpitchvol_t) == 0x64, "dynpitchvol_t size should be 0x64");
	}
}
