// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace server {
		enum HoverPoseFlags_t : std::uint8_t {
			HoverPoseFlags_t_eAngles = 0x2,
			HoverPoseFlags_t_eNone = 0x0,
			HoverPoseFlags_t_ePosition = 0x1
		};
	}
}