// generated - do not edit!
enum worldrenderer_AggregateInstanceStream_t {
	AGGREGATE_INSTANCE_STREAM_LIGHTMAPUV_UNORM16 = 0x1,
	AGGREGATE_INSTANCE_STREAM_NONE = 0x0,
	AGGREGATE_INSTANCE_STREAM_VERTEXBLEND_UNORM8 = 0x4,
	AGGREGATE_INSTANCE_STREAM_VERTEXTINT_UNORM8 = 0x2
}