// generated - do not edit!
enum server_LogicBranchListenerLastState_t {
	LOGIC_BRANCH_LISTENER_ALL_FALSE = 0x2,
	LOGIC_BRANCH_LISTENER_ALL_TRUE = 0x1,
	LOGIC_BRANCH_LISTENER_MIXED = 0x3,
	LOGIC_BRANCH_LISTENER_NOT_INIT = 0x0
}