// generated - do not edit!
enum server_OrientationUpdate_t {
	ORIENTATION_FACE_ENTITY = 0x8,
	ORIENTATION_FACE_PLAYER = 0x5,
	ORIENTATION_FIXED = 0x4,
	ORIENTATION_FORWARD_MOVEMENT_DIRECTION = 0x6,
	ORIENTATION_FORWARD_MOVEMENT_DIRECTION_AND_UP_CONTROL_POINT = 0x7,
	ORIENTATION_FORWARD_PATH = 0x0,
	ORIENTATION_FORWARD_PATH_AND_FIXED_PITCH = 0x1,
	ORIENTATION_FORWARD_PATH_AND_UP_CONTROL_POINT = 0x2,
	ORIENTATION_MATCH_CONTROL_POINT = 0x3
}