// generated - do not edit!
enum server_TransitionToPathNodeAction_t {
	TRANSITION_TO_PATH_NODE_ACTION_NONE = 0x0,
	TRANSITION_TO_PATH_NODE_ACTION_START_FORWARD = 0x1,
	TRANSITION_TO_PATH_NODE_ACTION_START_REVERSE = 0x2,
	TRANSITION_TO_PATH_NODE_TRANSITIONING = 0x3
}