#pragma once
#include "enums.hpp"
#include "typedefs.hpp"


class client_CGlobalLightBase {
    char vTable946[0x10];
    bool m_bSpotLight;
    char pad_947[0x3];
    Vector m_SpotLightOrigin;
    QAngle m_SpotLightAngles;
    Vector m_ShadowDirection;
    Vector m_AmbientDirection;
    Vector m_SpecularDirection;
    Vector m_InspectorSpecularDirection;
    float32 m_flSpecularPower;
    float32 m_flSpecularIndependence;
    Color m_SpecularColor;
    bool m_bStartDisabled;
    bool m_bEnabled;
    Color m_LightColor;
    Color m_AmbientColor1;
    Color m_AmbientColor2;
    Color m_AmbientColor3;
    char pad_948[0x2];
    float32 m_flSunDistance;
    float32 m_flFOV;
    float32 m_flNearZ;
    float32 m_flFarZ;
    bool m_bEnableShadows;
    bool m_bOldEnableShadows;
    bool m_bBackgroundClearNotRequired;
    char pad_949[0x1];
    float32 m_flCloudScale;
    float32 m_flCloud1Speed;
    float32 m_flCloud1Direction;
    float32 m_flCloud2Speed;
    float32 m_flCloud2Direction;
    char pad_950[0xc];
    float32 m_flAmbientScale1;
    float32 m_flAmbientScale2;
    float32 m_flGroundScale;
    float32 m_flLightScale;
    float32 m_flFoWDarkness;
    bool m_bEnableSeparateSkyboxFog;
    char pad_951[0x3];
    Vector m_vFowColor;
    Vector m_ViewOrigin;
    QAngle m_ViewAngles;
    float32 m_flViewFoV;
    Vector m_WorldPoints[8];
    char pad_952[0x358];
    Vector2D m_vFogOffsetLayer0;
    Vector2D m_vFogOffsetLayer1;
    char m_hEnvWind[0x4];
    char m_hEnvSky[0x4];
};
