#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class entity2_CEntityInstance;
class client_CGameSceneNode;
#include "client_CGameSceneNodeHandle.hpp"
#include "client_CNetworkOriginCellCoordQuantizedVector.hpp"
#include "client_CModelState.hpp"

class client_CSkeletonInstance {
    char vTable949[0x10];
    CTransformWS m_nodeToWorld;
    entity2_CEntityInstance* m_pOwner;
    client_CGameSceneNode* m_pParent;
    client_CGameSceneNode* m_pChild;
    client_CGameSceneNode* m_pNextSibling;
    char pad_950[0x28];
    client_CGameSceneNodeHandle m_hParent;
    client_CNetworkOriginCellCoordQuantizedVector m_vecOrigin;
    char pad_951[0x8];
    QAngle m_angRotation;
    float32 m_flScale;
    VectorWS m_vecAbsOrigin;
    QAngle m_angAbsRotation;
    float32 m_flAbsScale;
    Vector m_vecWrappedLocalOrigin;
    QAngle m_angWrappedLocalRotation;
    float32 m_flWrappedScale;
    int16_t m_nParentAttachmentOrBone;
    bool m_bDebugAbsOriginChanges;
    bool m_bDormant;
    bool m_bForceParentToBeNetworked;
    char pad_952[0x2];
    uint8_t m_nHierarchicalDepth;
    uint8_t m_nHierarchyType;
    uint8_t m_nDoNotSetAnimTimeInInvalidatePhysicsCount;
    char pad_953[0x2];
    CUtlStringToken m_name;
    char pad_954[0x40];
    CUtlStringToken m_hierarchyAttachName;
    float32 m_flZOffset;
    float32 m_flClientLocalScale;
    Vector m_vRenderOrigin;
    char end_pad_955[0x10];
    char vTable1093[0x10];
    client_CModelState m_modelState;
    bool m_bIsAnimationEnabled;
    bool m_bUseParentRenderBounds;
    bool m_bDisableSolidCollisionsForHierarchy;
    char pad_1094[0x1];
    CUtlStringToken m_materialGroup;
    uint8_t m_nHitboxSet;
    char end_pad_1095[0x97];
};
