#pragma once
#include "enums.hpp"
#include "typedefs.hpp"


class client_CNetworkTransmitComponent {
    void **__vftable_0;
    void **__vftable_1;
    void **__vftable_2;
    void **__vftable_3;
    void **__vftable_4;
    void **__vftable_5;
    void **__vftable_6;
    void **__vftable_7;
    void **__vftable_8;
    void **__vftable_9;
    void **__vftable_10;
    void **__vftable_11;
    void **__vftable_12;
    void **__vftable_13;
    void **__vftable_14;
    void **__vftable_15;
    void **__vftable_16;
    void **__vftable_17;
    void **__vftable_18;
    void **__vftable_19;
    void **__vftable_20;
    void **__vftable_21;
    void **__vftable_22;
    void **__vftable_23;
    void **__vftable_24;
    void **__vftable_25;
    void **__vftable_26;
    void **__vftable_27;
    void **__vftable_28;
    void **__vftable_29;
    void **__vftable_30;
    void **__vftable_31;
    void **__vftable_32;
    void **__vftable_33;
    void **__vftable_34;
    void **__vftable_35;
    void **__vftable_36;
    void **__vftable_37;
    void **__vftable_38;
    void **__vftable_39;
    void **__vftable_40;
    void **__vftable_41;
    void **__vftable_42;
    void **__vftable_43;
    void **__vftable_44;
    void **__vftable_45;
    void **__vftable_46;
    void **__vftable_47;
    char __vftable_pad[4];
    uint8_t m_nTransmitStateOwnedCounter;
    char end_pad_1811[0x4b];
};
