#pragma once
#include "enums.hpp"
#include "typedefs.hpp"


class compositematerialslib_CompositeMaterialInputLooseVariable_t {
    CUtlString m_strName;
    bool m_bExposeExternally;
    char pad_2690[0x7];
    CUtlString m_strExposedFriendlyName;
    CUtlString m_strExposedFriendlyGroupName;
    bool m_bExposedVariableIsFixedRange;
    char pad_2691[0x7];
    CUtlString m_strExposedVisibleWhenTrue;
    CUtlString m_strExposedHiddenWhenTrue;
    CUtlString m_strExposedValueList;
    compositematerialslib_CompositeMaterialInputLooseVariableType_t m_nVariableType;
    bool m_bValueBoolean;
    char pad_2692[0x3];
    int32_t m_nValueIntX;
    int32_t m_nValueIntY;
    int32_t m_nValueIntZ;
    int32_t m_nValueIntW;
    bool m_bHasFloatBounds;
    char pad_2693[0x3];
    float32 m_flValueFloatX;
    float32 m_flValueFloatX_Min;
    float32 m_flValueFloatX_Max;
    float32 m_flValueFloatY;
    float32 m_flValueFloatY_Min;
    float32 m_flValueFloatY_Max;
    float32 m_flValueFloatZ;
    float32 m_flValueFloatZ_Min;
    float32 m_flValueFloatZ_Max;
    float32 m_flValueFloatW;
    float32 m_flValueFloatW_Min;
    float32 m_flValueFloatW_Max;
    Color m_cValueColor4;
    compositematerialslib_CompositeMaterialVarSystemVar_t m_nValueSystemVar;
    char pad_2694[0x4];
    char m_strResourceMaterial[0xe0];
    CUtlString m_strTextureContentAssetPath;
    char m_strTextureRuntimeResourcePath[0xe0];
    CUtlString m_strTextureCompilationVtexTemplate;
    compositematerialslib_CompositeMaterialInputTextureType_t m_nTextureType;
    char pad_2695[0x4];
    CUtlString m_strString;
    CUtlString m_strPanoramaPanelPath;
    int32_t m_nPanoramaRenderRes;
    char end_pad_2696[0x4];
};
