#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"

class particles_C_OP_LightningSnapshotGenerator {
    void **__vftable_0;
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_691[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_692[0x2];
    bool m_bDisableOperator;
    char pad_693[0x1];
    CUtlString m_Notes;
    char end_pad_694[0x18];
    bool m_bRunOnce;
    char end_pad_707[0x7];
    int32_t m_nCPSnapshot;
    int32_t m_nCPStartPnt;
    int32_t m_nCPEndPnt;
    char pad_977[0x4];
    particleslib_CParticleCollectionFloatInput m_flSegments;
    particleslib_CParticleCollectionFloatInput m_flOffset;
    particleslib_CParticleCollectionFloatInput m_flOffsetDecay;
    particleslib_CParticleCollectionFloatInput m_flRecalcRate;
    particleslib_CParticleCollectionFloatInput m_flUVScale;
    particleslib_CParticleCollectionFloatInput m_flUVOffset;
    particleslib_CParticleCollectionFloatInput m_flSplitRate;
    particleslib_CParticleCollectionFloatInput m_flBranchTwist;
    particles_ParticleLightnintBranchBehavior_t m_nBranchBehavior;
    char pad_978[0x4];
    particleslib_CParticleCollectionFloatInput m_flRadiusStart;
    particleslib_CParticleCollectionFloatInput m_flRadiusEnd;
    particleslib_CParticleCollectionFloatInput m_flDedicatedPool;
};
