#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CPerParticleFloatInput.hpp"
#include "particleslib_CPerParticleFloatInput.hpp"
#include "particles_ParticleAttributeIndex_t.hpp"
#include "particles_ParticleAttributeIndex_t.hpp"

class particles_C_INIT_PositionPlaceOnGround {
    char vTable1798[0x8];
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_1799[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_1800[0x2];
    bool m_bDisableOperator;
    char pad_1801[0x1];
    CUtlString m_Notes;
    char end_pad_1802[0x18];
    int32_t m_nAssociatedEmitterIndex;
    char end_pad_1806[0x4];
    particleslib_CPerParticleFloatInput m_flOffset;
    particleslib_CPerParticleFloatInput m_flMaxTraceLength;
    char m_CollisionGroupName[128];
    particles_ParticleTraceSet_t m_nTraceSet;
    char pad_1930[0xc];
    particles_ParticleTraceMissBehavior_t m_nTraceMissBehavior;
    bool m_bIncludeWater;
    bool m_bSetNormal;
    char pad_1931[0x2];
    particles_ParticleAttributeIndex_t m_nAttribute;
    bool m_bSetPXYZOnly;
    bool m_bTraceAlongNormal;
    char pad_1932[0x2];
    particles_ParticleAttributeIndex_t m_nTraceDirectionAttribute;
    bool m_bOffsetonColOnly;
    char pad_1933[0x3];
    float32 m_flOffsetByRadiusFactor;
    int32_t m_nPreserveOffsetCP;
    int32_t m_nIgnoreCP;
    char end_pad_1934[0x4];
};
