#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
class particleslib_CParticleCollectionVecInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionVecInput.hpp"

class particles_C_OP_RemapAverageHitboxSpeedtoCP {
    char vTable1798[0x8];
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_1799[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_1800[0x2];
    bool m_bDisableOperator;
    char pad_1801[0x1];
    CUtlString m_Notes;
    char end_pad_1802[0x18];
    bool m_bRunOnce;
    char end_pad_1815[0x7];
    int32_t m_nInControlPointNumber;
    int32_t m_nOutControlPointNumber;
    int32_t m_nField;
    particles_ParticleHitboxDataSelection_t m_nHitboxDataType;
    particleslib_CParticleCollectionFloatInput m_flInputMin;
    particleslib_CParticleCollectionFloatInput m_flInputMax;
    particleslib_CParticleCollectionFloatInput m_flOutputMin;
    particleslib_CParticleCollectionFloatInput m_flOutputMax;
    int32_t m_nHeightControlPointNumber;
    char pad_2155[0x4];
    particleslib_CParticleCollectionVecInput m_vecComparisonVelocity;
    char m_HitboxSetName[128];
};
