#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particles_CParticleVisibilityInputs.hpp"
#include "particleslib_CPerParticleVecInput.hpp"
#include "particleslib_CPerParticleVecInput.hpp"
#include "particleslib_CPerParticleFloatInput.hpp"
#include "particleslib_CPerParticleFloatInput.hpp"
#include "particleslib_CPerParticleFloatInput.hpp"
#include "particleslib_CPerParticleFloatInput.hpp"
#include "particleslib_CPerParticleVecInput.hpp"

class particles_C_OP_GameDecalRenderer {
    char vTable1798[0x8];
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_1799[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_1800[0x2];
    bool m_bDisableOperator;
    char pad_1801[0x1];
    CUtlString m_Notes;
    char end_pad_1802[0x18];
    particles_CParticleVisibilityInputs VisibilityInputs;
    bool m_bCannotBeRefracted;
    bool m_bSkipRenderingOnMobile;
    char end_pad_1787[0x6];
    CGlobalSymbol m_sDecalGroupName;
    particles_EventTypeSelection_t m_nEventType;
    char pad_2066[0x4];
    particles_ParticleCollisionMask_t m_nInteractionMask;
    particles_ParticleCollisionGroup_t m_nCollisionGroup;
    char pad_2067[0x4];
    particleslib_CPerParticleVecInput m_vecStartPos;
    particleslib_CPerParticleVecInput m_vecEndPos;
    particleslib_CPerParticleFloatInput m_flTraceBloat;
    particleslib_CPerParticleFloatInput m_flDecalSize;
    particleslib_CPerParticleFloatInput m_nDecalGroupIndex;
    particleslib_CPerParticleFloatInput m_flDecalRotation;
    particleslib_CPerParticleVecInput m_vModulationColor;
    bool m_bUseGameDefaultDecalSize;
    bool m_bRandomDecalRotation;
    bool m_bRandomlySelectDecalInGroup;
    bool m_bNoDecalsOnOwner;
    bool m_bVisualizeTraces;
    char end_pad_2068[0x3];
};
