#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CPerParticleFloatInput.hpp"

class particles_C_OP_MovementPlaceOnGround {
    char vTable1798[0x8];
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_1799[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_1800[0x2];
    bool m_bDisableOperator;
    char pad_1801[0x1];
    CUtlString m_Notes;
    char end_pad_1802[0x18];
    particleslib_CPerParticleFloatInput m_flOffset;
    float32 m_flMaxTraceLength;
    float32 m_flTolerance;
    float32 m_flTraceOffset;
    float32 m_flLerpRate;
    char m_CollisionGroupName[128];
    particles_ParticleTraceSet_t m_nTraceSet;
    int32_t m_nRefCP1;
    int32_t m_nRefCP2;
    int32_t m_nLerpCP;
    char pad_2106[0x8];
    particles_ParticleTraceMissBehavior_t m_nTraceMissBehavior;
    bool m_bIncludeShotHull;
    bool m_bIncludeWater;
    char pad_2107[0x2];
    bool m_bSetNormal;
    bool m_bScaleOffset;
    char pad_2108[0x2];
    int32_t m_nPreserveOffsetCP;
    int32_t m_nIgnoreCP;
    char end_pad_2109[0x4];
};
