#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
class particleslib_CParticleCollectionVecInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleTransformInput.hpp"
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particleslib_CParticleCollectionVecInput.hpp"
#include "particles_ParticleAttributeIndex_t.hpp"
#include "particles_ParticleAttributeIndex_t.hpp"

class particles_C_OP_PositionLock {
    char vTable1798[0x8];
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_1799[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_1800[0x2];
    bool m_bDisableOperator;
    char pad_1801[0x1];
    CUtlString m_Notes;
    char end_pad_1802[0x18];
    particleslib_CParticleTransformInput m_TransformInput;
    float32 m_flStartTime_min;
    float32 m_flStartTime_max;
    float32 m_flStartTime_exp;
    float32 m_flEndTime_min;
    float32 m_flEndTime_max;
    float32 m_flEndTime_exp;
    float32 m_flRange;
    char pad_2140[0x4];
    particleslib_CParticleCollectionFloatInput m_flRangeBias;
    float32 m_flJumpThreshold;
    float32 m_flPrevPosScale;
    bool m_bLockRot;
    char pad_2141[0x7];
    particleslib_CParticleCollectionVecInput m_vecScale;
    particles_ParticleAttributeIndex_t m_nFieldOutput;
    particles_ParticleAttributeIndex_t m_nFieldOutputPrev;
};
