#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"

class particles_C_INIT_StatusEffect {
    char vTable1797[0x8];
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_1798[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_1799[0x2];
    bool m_bDisableOperator;
    char pad_1800[0x1];
    CUtlString m_Notes;
    char end_pad_1801[0x18];
    int32_t m_nAssociatedEmitterIndex;
    char end_pad_1805[0x4];
    particles_Detail2Combo_t m_nDetail2Combo;
    float32 m_flDetail2Rotation;
    float32 m_flDetail2Scale;
    float32 m_flDetail2BlendFactor;
    float32 m_flColorWarpIntensity;
    float32 m_flDiffuseWarpBlendToFull;
    float32 m_flEnvMapIntensity;
    float32 m_flAmbientScale;
    Color m_specularColor;
    float32 m_flSpecularScale;
    float32 m_flSpecularExponent;
    float32 m_flSpecularExponentBlendToFull;
    float32 m_flSpecularBlendToFull;
    Color m_rimLightColor;
    float32 m_flRimLightScale;
    float32 m_flReflectionsTintByBaseBlendToNone;
    float32 m_flMetalnessBlendToFull;
    float32 m_flSelfIllumBlendToFull;
    char end_pad_1980[0x18];
};
