#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particles_ParticleAttributeIndex_t.hpp"
#include "particleslib_CParticleTransformInput.hpp"
#include "particleslib_CParticleTransformInput.hpp"

class particles_C_INIT_RemapTransformToVector {
    void **__vftable_0;
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_691[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_692[0x2];
    bool m_bDisableOperator;
    char pad_693[0x1];
    CUtlString m_Notes;
    char end_pad_694[0x18];
    int32_t m_nAssociatedEmitterIndex;
    char end_pad_698[0x4];
    particles_ParticleAttributeIndex_t m_nFieldOutput;
    Vector m_vInputMin;
    Vector m_vInputMax;
    Vector m_vOutputMin;
    Vector m_vOutputMax;
    char pad_853[0x4];
    particleslib_CParticleTransformInput m_TransformInput;
    particleslib_CParticleTransformInput m_LocalSpaceTransform;
    float32 m_flStartTime;
    float32 m_flEndTime;
    particles_ParticleSetMethod_t m_nSetMethod;
    bool m_bOffset;
    bool m_bAccelerate;
    char pad_854[0x2];
    float32 m_flRemapBias;
    char end_pad_855[0x4];
};
