#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class particleslib_CParticleCollectionFloatInput;
class particleslib_CParticleCollectionVecInput;
#include "particleslib_CParticleCollectionFloatInput.hpp"
#include "particles_CParticleVisibilityInputs.hpp"
#include "particles_ParticleAttributeIndex_t.hpp"
#include "particleslib_CParticleCollectionVecInput.hpp"

class particles_C_OP_RenderDeferredLight {
    char vTable1797[0x8];
    particleslib_CParticleCollectionFloatInput m_flOpStrength;
    particles_ParticleEndcapMode_t m_nOpEndCapState;
    float32 m_flOpStartFadeInTime;
    float32 m_flOpEndFadeInTime;
    float32 m_flOpStartFadeOutTime;
    float32 m_flOpEndFadeOutTime;
    float32 m_flOpFadeOscillatePeriod;
    bool m_bNormalizeToStopTime;
    char pad_1798[0x3];
    float32 m_flOpTimeOffsetMin;
    float32 m_flOpTimeOffsetMax;
    int32_t m_nOpTimeOffsetSeed;
    int32_t m_nOpTimeScaleSeed;
    float32 m_flOpTimeScaleMin;
    float32 m_flOpTimeScaleMax;
    char pad_1799[0x2];
    bool m_bDisableOperator;
    char pad_1800[0x1];
    CUtlString m_Notes;
    char end_pad_1801[0x18];
    particles_CParticleVisibilityInputs VisibilityInputs;
    bool m_bCannotBeRefracted;
    bool m_bSkipRenderingOnMobile;
    char end_pad_1786[0x6];
    bool m_bUseAlphaTestWindow;
    bool m_bUseTexture;
    char pad_2206[0x2];
    float32 m_flRadiusScale;
    float32 m_flAlphaScale;
    particles_ParticleAttributeIndex_t m_nAlpha2Field;
    particleslib_CParticleCollectionVecInput m_vecColorScale;
    particles_ParticleColorBlendType_t m_nColorBlendType;
    float32 m_flLightDistance;
    float32 m_flStartFalloff;
    float32 m_flDistanceFalloff;
    float32 m_flSpotFoV;
    particles_ParticleAttributeIndex_t m_nAlphaTestPointField;
    particles_ParticleAttributeIndex_t m_nAlphaTestRangeField;
    particles_ParticleAttributeIndex_t m_nAlphaTestSharpnessField;
    char m_hTexture[0x8];
    int32_t m_nHSVShiftControlPoint;
    char end_pad_2207[0x4];
};
