#pragma once
#include "enums.hpp"
#include "typedefs.hpp"

class client_CSkeletonInstance;
#include "server_CAnimGraphNetworkedVariables.hpp"
#include "client_ExternalAnimGraphHandle_t.hpp"
#include "animationsystem_HSequence.hpp"
#include "entity2_GameTime_t.hpp"
#include "entity2_GameTick_t.hpp"
#include "resourcefile_ResourceId_t.hpp"

class server_CBaseAnimGraphController {
    char pad_1571[0x8];
    client_CSkeletonInstance* m_pSkeletonInstance;
    void **__vftable_0;
    client_AnimationAlgorithm_t m_nAnimationAlgorithm;
    char pad_2954[0x7];
    server_CAnimGraphNetworkedVariables m_animGraphNetworkedVars;
    char m_pAnimGraphInstance[0x8];
    char pad_2955[0x58];
    client_ExternalAnimGraphHandle_t m_nNextExternalGraphHandle;
    char pad_2956[0x4];
    char m_vecSecondarySkeletonNames[0x18];
    char m_vecSecondarySkeletons[0x18];
    int32_t m_nSecondarySkeletonMasterCount;
    float32 m_flSoundSyncTime;
    uint32_t m_nActiveIKChainMask;
    animationsystem_HSequence m_hSequence;
    entity2_GameTime_t m_flSeqStartTime;
    float32 m_flSeqFixedCycle;
    client_AnimLoopMode_t m_nAnimLoopMode;
    CNetworkedQuantizedFloat m_flPlaybackRate;
    char pad_2957[0x4];
    client_SequenceFinishNotifyState_t m_nNotifyState;
    bool m_bNetworkedAnimationInputsChanged;
    bool m_bNetworkedSequenceChanged;
    bool m_bLastUpdateSkipped;
    bool m_bSequenceFinished;
    char pad_2958[0x3];
    entity2_GameTick_t m_nPrevAnimUpdateTick;
    char pad_2959[0x29c];
    char m_hGraphDefinitionAG2[0x8];
    char m_serializedPoseRecipeAG2[0x18];
    int32_t m_nSerializePoseRecipeSizeAG2;
    int32_t m_nSerializePoseRecipeVersionAG2;
    int32_t m_nServerGraphInstanceIteration;
    int32_t m_nServerSerializationContextIteration;
    resourcefile_ResourceId_t m_primaryGraphId;
    char m_vecExternalGraphIds[0x18];
    char m_vecExternalClipIds[0x18];
    CGlobalSymbol m_sAnimGraph2Identifier;
    char pad_2960[0x220];
    char m_vecExternalGraphs[0x18];
    char pad_2961[0x20];
};
