// generated - do not edit!
enum particles_ModelHitboxType_t {
	MODEL_HITBOX_TYPE_RAW_BONES = 0x1,
	MODEL_HITBOX_TYPE_RENDERBOUNDS = 0x2,
	MODEL_HITBOX_TYPE_SNAPSHOT = 0x3,
	MODEL_HITBOX_TYPE_STANDARD = 0x0
}