// generated - do not edit!
enum particles_ParticleOrientationSetMode_t {
	PARTICLE_ORIENTATION_SET_FROM_NORMAL = 0x1,
	PARTICLE_ORIENTATION_SET_FROM_ROTATIONS = 0x2,
	PARTICLE_ORIENTATION_SET_FROM_VELOCITY = 0x0,
	PARTICLE_ORIENTATION_SET_NONE = 0xffffffff
}