// generated - do not edit!
enum particles_ParticleLightFogLightingMode_t {
	PARTICLE_LIGHT_FOG_LIGHTING_MODE_DYNAMIC = 0x2,
	PARTICLE_LIGHT_FOG_LIGHTING_MODE_DYNAMIC_NOSHADOWS = 0x4,
	PARTICLE_LIGHT_FOG_LIGHTING_MODE_NONE = 0x0
}