// generated - do not edit!
enum particles_ParticleAttrBoxFlags_t {
	PARTICLE_ATTR_BOX_FLAGS_ASLEEP = 0x8,
	PARTICLE_ATTR_BOX_FLAGS_ELECTRIFIED = 0x4,
	PARTICLE_ATTR_BOX_FLAGS_FROZEN = 0x10,
	PARTICLE_ATTR_BOX_FLAGS_NONE = 0x0,
	PARTICLE_ATTR_BOX_FLAGS_ON_FIRE = 0x2,
	PARTICLE_ATTR_BOX_FLAGS_TIMED_DECAY = 0x20,
	PARTICLE_ATTR_BOX_FLAGS_WATER = 0x1
}