// generated - do not edit!
enum particles_ParticleLightingQuality_t {
	PARTICLE_LIGHTING_ADD_EXTRA_LIGHT = 0x4,
	PARTICLE_LIGHTING_OVERRIDE_COLOR = 0x3,
	PARTICLE_LIGHTING_OVERRIDE_POSITION = 0x2,
	PARTICLE_LIGHTING_PER_PARTICLE = 0x0,
	PARTICLE_LIGHTING_PER_PIXEL = 0xffffffff,
	PARTICLE_LIGHTING_PER_VERTEX = 0x1
}