// generated - do not edit!
enum particles_ParticleCollisionGroup_t {
	PARTICLE_COLLISION_GROUP_DEBRIS = 0x5,
	PARTICLE_COLLISION_GROUP_DEFAULT = 0x4,
	PARTICLE_COLLISION_GROUP_INTERACTIVE = 0x7,
	PARTICLE_COLLISION_GROUP_NPC = 0xc,
	PARTICLE_COLLISION_GROUP_PLAYER = 0x8,
	PARTICLE_COLLISION_GROUP_PROPS = 0x18,
	PARTICLE_COLLISION_GROUP_VEHICLE = 0xa
}