// generated - do not edit!
enum particles_SetStatisticExpressionType_t {
	SET_EXPRESSION_MAX = 0x6,
	SET_EXPRESSION_MEAN = 0x1,
	SET_EXPRESSION_MEDIAN = 0x2,
	SET_EXPRESSION_MIN = 0x5,
	SET_EXPRESSION_MODE = 0x3,
	SET_EXPRESSION_STANDARD_DEVIATION = 0x4,
	SET_EXPRESSION_SUM = 0x0,
	SET_EXPRESSION_UNINITIALIZED = 0xffffffff
}