// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace scenesystem {
			// Class size: 0x30
			namespace CSSDSMsg_PreLayer /*: public CS2::scenesystem::CSSDSMsg_LayerBase*/ {
				// NO SCHEMA DATA FOUND!
			}
		}
	}
}
