// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace resourcefile {
		class CExampleSchemaVData_PolymorphicBase  {
		public:
			S2_PAD(0x8);
			int32_t m_nBase; // 0x8 | Schema_Builtin | Size: 0x4
			S2_PAD(0x4); // End padding
		};
		static_assert(offsetof(CS2::resourcefile::CExampleSchemaVData_PolymorphicBase, m_nBase) == 0x8, "m_nBase in CExampleSchemaVData_PolymorphicBase should be at offset 0x8");
		static_assert(sizeof(CS2::resourcefile::CExampleSchemaVData_PolymorphicBase) == 0x10, "CExampleSchemaVData_PolymorphicBase size should be 0x10");
	}
}
