// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0xF08
			namespace C_FuncConveyor /*: public CS2::client::C_BaseModelEntity*/ {
				constexpr std::ptrdiff_t m_vecMoveDirEntitySpace = 0xec8; // GlobalTypes::Vector m_vecMoveDirEntitySpace; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flTargetSpeed = 0xed4; // float32 m_flTargetSpeed; |  0xed4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nTransitionStartTick = 0xed8; // entity2::GameTick_t m_nTransitionStartTick; |  Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_nTransitionDurationTicks = 0xedc; // int32_t m_nTransitionDurationTicks; |  0xedc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flTransitionStartSpeed = 0xee0; // float32 m_flTransitionStartSpeed; |  0xee0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hConveyorModels = 0xee8; // client::C_NetworkUtlVectorBase< client.dll::CHandle< C_BaseEntity > > m_hConveyorModels; |  Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_flCurrentConveyorOffset = 0xf00; // float32 m_flCurrentConveyorOffset; |  0xf00 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flCurrentConveyorSpeed = 0xf04; // float32 m_flCurrentConveyorSpeed; |  0xf04 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
