// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace client {
			// Class size: 0x28
			namespace CPhysicsBodyGameMarkupData /**/ {
				constexpr std::ptrdiff_t m_PhysicsBodyMarkupByBoneName = 0x0; // GlobalTypes::CUtlOrderedMap  | Schema_Atomic | Size: 0x28
			}
		}
	}
}
