// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animationsystem {
			// Class size: 0x2C
			namespace CAnimMovement /**/ {
				constexpr std::ptrdiff_t endframe = 0x0; // int32_t endframe; |  0x0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t motionflags = 0x4; // int32_t motionflags; |  0x4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t v0 = 0x8; // float32 v0; |  0x8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t v1 = 0xc; // float32 v1; |  0xc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t angle = 0x10; // float32 angle; |  0x10 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t vector = 0x14; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t position = 0x20; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
			}
		}
	}
}
