// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace pulse_system {
			// Class size: 0x1
			namespace CPulseTestFuncs_LibraryA /**/ {
				// NO SCHEMA DATA FOUND!
			}
		}
	}
}
