// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace pulse_system {
			// Class size: 0x48
			namespace CPulseCell_Val_TestDomainGetEntityName /*: public CS2::pulse_runtime_lib::CPulseCell_BaseValue*/ {
				// NO SCHEMA DATA FOUND!
			}
		}
	}
}
