// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace soundsystem_lowlevel {
			// Class size: 0x20
			namespace CVMixBaseProcessorDesc /**/ {
				constexpr std::ptrdiff_t m_name = 0x8; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nChannels = 0x14; // int32_t m_nChannels; |  0x14 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flxfade = 0x18; // float32 m_flxfade; |  0x18 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
