// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace soundsystem_lowlevel {
			// Class size: 0x10
			namespace CVMixAutomaticControlInput /**/ {
				constexpr std::ptrdiff_t m_name = 0x0; // GlobalTypes::CUtlString  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nControlInputIndex = 0x8; // int32_t m_nControlInputIndex; |  0x8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bIsTrackSend = 0xc; // bool m_bIsTrackSend; |  0xc | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bIsStackVar = 0xd; // bool m_bIsStackVar; |  0xd | Schema_Builtin | Size: 0x1
			}
		}
	}
}
