// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace soundsystem_lowlevel {
			// Class size: 0x24
			namespace VMixDynamicsCompressorDesc_t /**/ {
				constexpr std::ptrdiff_t m_fldbOutputGain = 0x0; // float32 m_fldbOutputGain; |  0x0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fldbCompressionThreshold = 0x4; // float32 m_fldbCompressionThreshold; |  0x4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fldbKneeWidth = 0x8; // float32 m_fldbKneeWidth; |  0x8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flCompressionRatio = 0xc; // float32 m_flCompressionRatio; |  0xc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flAttackTimeMS = 0x10; // float32 m_flAttackTimeMS; |  0x10 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flReleaseTimeMS = 0x14; // float32 m_flReleaseTimeMS; |  0x14 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flRMSTimeMS = 0x18; // float32 m_flRMSTimeMS; |  0x18 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flWetMix = 0x1c; // float32 m_flWetMix; |  0x1c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bPeakMode = 0x20; // bool m_bPeakMode; |  0x20 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
