// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace toolscene {
			// Class size: 0x168
			namespace CToolSceneLightRig /**/ {
				constexpr std::ptrdiff_t m_nRigType = 0x8; // toolscene::LightRigType_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_Suns = 0x10; // GlobalTypes::CUtlVector<toolscene::CLightRigSunLight>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_PointLights = 0x28; // GlobalTypes::CUtlVector<toolscene::CLightRigPointLight>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_SpotLights = 0x40; // GlobalTypes::CUtlVector<toolscene::CLightRigSpotLight>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_Background = 0x58; // toolscene::CLightRigBackground  | Schema_DeclaredClass | Size: 0x5
				constexpr std::ptrdiff_t m_Grid = 0x5d; // toolscene::CLightRigGrid  | Schema_DeclaredClass | Size: 0x5
				constexpr std::ptrdiff_t m_Exposure = 0x64; // toolscene::CLightRigExposure  | Schema_DeclaredClass | Size: 0xc
				constexpr std::ptrdiff_t m_PostProcessing = 0x70; // toolscene::CLightRigPostProcessing  | Schema_DeclaredClass | Size: 0x8
				constexpr std::ptrdiff_t m_Sky = 0x78; // toolscene::CLightRigSky  | Schema_DeclaredClass | Size: 0x8
				constexpr std::ptrdiff_t m_BackgroundMap = 0x80; // toolscene::CLightRigVMap  | Schema_DeclaredClass | Size: 0xe8
			}
		}
	}
}
