// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace soundsystem {
		class CDSPPresetMixgroupModifierTable  {
		public:
			// GlobalTypes::CUtlVector< soundsystem::CDspPresetModifierList > m_table; // 0x0 | Schema_Atomic | Size: 0x18
			char  m_table[0x18]; // 0x0 | Schema_Atomic | Size: 0x18
		};
		static_assert(offsetof(CS2::soundsystem::CDSPPresetMixgroupModifierTable, m_table) == 0x0, "m_table in CDSPPresetMixgroupModifierTable should be at offset 0x0");
		static_assert(sizeof(CS2::soundsystem::CDSPPresetMixgroupModifierTable) == 0x18, "CDSPPresetMixgroupModifierTable size should be 0x18");
	}
}
