// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace Interfaces {
		namespace client {
			constexpr std::ptrdiff_t ClientToolsInfo_001 = 0x1beac20; 
			constexpr std::ptrdiff_t EmptyWorldService001_Client = 0x1ba5e80; 
			constexpr std::ptrdiff_t GameClientExports001 = 0x1be7900; 
			constexpr std::ptrdiff_t LegacyGameUI001 = 0x1c063d0; 
			constexpr std::ptrdiff_t Source2Client002 = 0x1e2ddb0; 
			constexpr std::ptrdiff_t Source2ClientConfig001 = 0x1dc77e0; 
			constexpr std::ptrdiff_t Source2ClientPrediction001 = 0x1bf1ed0; 
			constexpr std::ptrdiff_t Source2ClientUI001 = 0x1c04870; 
		}
	}
}
