// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace Interfaces {
		namespace soundsystem {
			constexpr std::ptrdiff_t SoundOpSystem001 = 0x3eb4a0; 
			constexpr std::ptrdiff_t SoundOpSystemEdit001 = 0x3eb380; 
			constexpr std::ptrdiff_t SoundSystem001 = 0x3eae60; 
			constexpr std::ptrdiff_t VMixEditTool001 = 0x485ed80b; 
		}
	}
}
