// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace Interfaces {
		namespace vphysics2 {
			constexpr std::ptrdiff_t VPhysics2_Handle_Interface_001 = 0x3e4120; 
			constexpr std::ptrdiff_t VPhysics2_Interface_001 = 0x3e4160; 
		}
	}
}
