// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/particleslib/CParticleCollectionFloatInput.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace particleslib {
		class CParticleCollectionRendererFloatInput : public CS2::particleslib::CParticleCollectionFloatInput {
		public:
		};
		static_assert(sizeof(CS2::particleslib::CParticleCollectionRendererFloatInput) == 0x170, "CParticleCollectionRendererFloatInput size should be 0x170");
	}
}
