// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/particleslib/CParticleVecInput.hpp>



namespace CS2 {
	namespace particleslib {
		class CPerParticleVecInput : public CS2::particleslib::CParticleVecInput {
		public:
		};
		static_assert(sizeof(CS2::particleslib::CPerParticleVecInput) == 0x6B8, "CPerParticleVecInput size should be 0x6B8");
	}
}
