// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace particleslib {
			// Class size: 0x6B8
			namespace CParticleCollectionVecInput /*: public CS2::particleslib::CParticleVecInput*/ {
				// NO SCHEMA DATA FOUND!
			}
		}
	}
}
