// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/pulse_runtime_lib/CPulseCell_BaseFlow.hpp>



namespace CS2 {
	namespace pulse_system {
		class CPulseCell_Test_MultiInflow_NoDefault : public CS2::pulse_runtime_lib::CPulseCell_BaseFlow {
		public:
		};
		static_assert(sizeof(CS2::pulse_system::CPulseCell_Test_MultiInflow_NoDefault) == 0x48, "CPulseCell_Test_MultiInflow_NoDefault size should be 0x48");
	}
}
