// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x868
			namespace CBaseToggle /*: public CS2::server::CBaseModelEntity*/ {
				constexpr std::ptrdiff_t m_toggle_state = 0x7e8; // server::TOGGLE_STATE m_toggle_state; |  Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_flMoveDistance = 0x7ec; // float32 m_flMoveDistance; |  0x7ec | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flWait = 0x7f0; // float32 m_flWait; |  0x7f0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flLip = 0x7f4; // float32 m_flLip; |  0x7f4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bAlwaysFireBlockedOutputs = 0x7f8; // bool m_bAlwaysFireBlockedOutputs; |  0x7f8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_vecPosition1 = 0x7fc; // GlobalTypes::Vector m_vecPosition1; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vecPosition2 = 0x808; // GlobalTypes::Vector m_vecPosition2; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vecMoveAng = 0x814; // GlobalTypes::QAngle m_vecMoveAng; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vecAngle1 = 0x820; // GlobalTypes::QAngle m_vecAngle1; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vecAngle2 = 0x82c; // GlobalTypes::QAngle m_vecAngle2; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flHeight = 0x838; // float32 m_flHeight; |  0x838 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hActivator = 0x83c; // server::CHandle< server::CBaseEntity > m_hActivator; |  Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_vecFinalDest = 0x840; // GlobalTypes::Vector m_vecFinalDest; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vecFinalAngle = 0x84c; // GlobalTypes::QAngle m_vecFinalAngle; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_movementType = 0x858; // int32_t m_movementType; |  0x858 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_sMaster = 0x860; // GlobalTypes::CUtlSymbolLarge m_sMaster; |  Schema_Atomic | Size: 0x8
			}
		}
	}
}
