// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x7D0
			namespace CBeam /*: public CS2::server::CBaseModelEntity*/ {
				constexpr std::ptrdiff_t m_flFrameRate = 0x730; // float32 m_flFrameRate; |  0x730 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flHDRColorScale = 0x734; // float32 m_flHDRColorScale; |  0x734 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFireTime = 0x738; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flDamage = 0x73c; // float32 m_flDamage; |  0x73c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nNumBeamEnts = 0x740; // uint8_t m_nNumBeamEnts; |  0x740 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_hBaseMaterial = 0x748; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nHaloIndex = 0x750; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeIMaterial2>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nBeamType = 0x758; // client::BeamType_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_nBeamFlags = 0x75c; // uint32_t m_nBeamFlags; |  0x75c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hAttachEntity = 0x760; // GlobalTypes::CHandle  | Schema_FixedArray | Size: 0x28
				constexpr std::ptrdiff_t m_nAttachIndex = 0x788; // GlobalTypes::AttachmentHandle_t[10]  | Schema_FixedArray | Size: 0x64
				constexpr std::ptrdiff_t m_fWidth = 0x794; // float32 m_fWidth; |  0x794 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fEndWidth = 0x798; // float32 m_fEndWidth; |  0x798 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fFadeLength = 0x79c; // float32 m_fFadeLength; |  0x79c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fHaloScale = 0x7a0; // float32 m_fHaloScale; |  0x7a0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fAmplitude = 0x7a4; // float32 m_fAmplitude; |  0x7a4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fStartFrame = 0x7a8; // float32 m_fStartFrame; |  0x7a8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_fSpeed = 0x7ac; // float32 m_fSpeed; |  0x7ac | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flFrame = 0x7b0; // float32 m_flFrame; |  0x7b0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nClipStyle = 0x7b4; // client::BeamClipStyle_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bTurnedOff = 0x7b8; // bool m_bTurnedOff; |  0x7b8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_vecEndPos = 0x7bc; // GlobalTypes::VectorWS  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_hEndEntity = 0x7c8; // GlobalTypes::CHandle<server::CBaseEntity>  | Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_nDissolveType = 0x7cc; // int32_t m_nDissolveType; |  0x7cc | Schema_Builtin | Size: 0x4
			}
		}
	}
}
