// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0xCC0
			namespace CBodyComponentBaseAnimGraph /*: public CS2::server::CBodyComponentSkeletonInstance*/ {
				constexpr std::ptrdiff_t m_animationController = 0x510; // server::CBaseAnimGraphController  | Schema_DeclaredClass | Size: 0x7b0
			}
		}
	}
}
