// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x78
			namespace CBtActionParachutePositioning /*: public CS2::server::CBtNode*/ {
				constexpr std::ptrdiff_t m_ActionTimer = 0x58; // server::CountdownTimer  | Schema_DeclaredClass | Size: 0x18
			}
		}
	}
}
