// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x540
			namespace CCSPlayerResource /*: public CS2::server::CBaseEntity*/ {
				constexpr std::ptrdiff_t m_bHostageAlive = 0x4a8; // bool m_bHostageAlive[12]; |  0x4a8 | Schema_FixedArray | Size: 0xc
				constexpr std::ptrdiff_t m_isHostageFollowingSomeone = 0x4b4; // bool m_isHostageFollowingSomeone[12]; |  0x4b4 | Schema_FixedArray | Size: 0xc
				constexpr std::ptrdiff_t m_iHostageEntityIDs = 0x4c0; // GlobalTypes::CEntityIndex[12]  | Schema_FixedArray | Size: 0x30
				constexpr std::ptrdiff_t m_bombsiteCenterA = 0x4f0; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_bombsiteCenterB = 0x4fc; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_hostageRescueX = 0x508; // int32_t m_hostageRescueX[4]; |  0x508 | Schema_FixedArray | Size: 0x10
				constexpr std::ptrdiff_t m_hostageRescueY = 0x518; // int32_t m_hostageRescueY[4]; |  0x518 | Schema_FixedArray | Size: 0x10
				constexpr std::ptrdiff_t m_hostageRescueZ = 0x528; // int32_t m_hostageRescueZ[4]; |  0x528 | Schema_FixedArray | Size: 0x10
				constexpr std::ptrdiff_t m_bEndMatchNextMapAllVoted = 0x538; // bool m_bEndMatchNextMapAllVoted; |  0x538 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_foundGoalPositions = 0x539; // bool m_foundGoalPositions; |  0x539 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
