// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0xA08
			namespace CDynamicNavConnectionsVolume /*: public CS2::server::CTriggerMultiple*/ {
				constexpr std::ptrdiff_t m_iszConnectionTarget = 0x9d0; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_vecConnections = 0x9d8; // GlobalTypes::CUtlVector<server::DynamicVolumeDef_t>  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_sTransitionType = 0x9f0; // GlobalTypes::CGlobalSymbol  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_bConnectionsEnabled = 0x9f8; // bool m_bConnectionsEnabled; |  0x9f8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flTargetAreaSearchRadius = 0x9fc; // float32 m_flTargetAreaSearchRadius; |  0x9fc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flUpdateDistance = 0xa00; // float32 m_flUpdateDistance; |  0xa00 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flMaxConnectionDistance = 0xa04; // float32 m_flMaxConnectionDistance; |  0xa04 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
