// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x4F8
			namespace CEnvSplash /*: public CS2::server::CPointEntity*/ {
				constexpr std::ptrdiff_t m_flScale = 0x4f0; // float32 m_flScale; |  0x4f0 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
