// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x848
			namespace CFuncElectrifiedVolume /*: public CS2::server::CFuncBrush*/ {
				constexpr std::ptrdiff_t m_EffectName = 0x810; // GlobalTypes::CUtlSymbolLarge m_EffectName; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_EffectInterpenetrateName = 0x818; // GlobalTypes::CUtlSymbolLarge m_EffectInterpenetrateName; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_EffectZapName = 0x820; // GlobalTypes::CUtlSymbolLarge m_EffectZapName; |  Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_iszEffectSource = 0x828; // GlobalTypes::CUtlSymbolLarge m_iszEffectSource; |  Schema_Atomic | Size: 0x8
			}
		}
	}
}
