// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x7F8
			namespace CFuncPlatRot /*: public CS2::server::CFuncPlat*/ {
				constexpr std::ptrdiff_t m_end = 0x7e0; // GlobalTypes::QAngle  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_start = 0x7ec; // GlobalTypes::QAngle  | Schema_Atomic | Size: 0xc
			}
		}
	}
}
