// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x850
			namespace CMarkupVolumeWithRef /*: public CS2::server::CMarkupVolumeTagged*/ {
				constexpr std::ptrdiff_t m_bUseRef = 0x830; // bool m_bUseRef; |  0x830 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_vRefPosEntitySpace = 0x834; // GlobalTypes::Vector m_vRefPosEntitySpace; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vRefPosWorldSpace = 0x840; // GlobalTypes::Vector m_vRefPosWorldSpace; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flRefDot = 0x84c; // float32 m_flRefDot; |  0x84c | Schema_Builtin | Size: 0x4
			}
		}
	}
}
