// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0xC10
			namespace CRagdollPropAttached /*: public CS2::server::CRagdollProp*/ {
				constexpr std::ptrdiff_t m_boneIndexAttached = 0xbd0; // uint32_t m_boneIndexAttached; |  0xbd0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_ragdollAttachedObjectIndex = 0xbd4; // uint32_t m_ragdollAttachedObjectIndex; |  0xbd4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_attachmentPointBoneSpace = 0xbd8; // GlobalTypes::Vector m_attachmentPointBoneSpace; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_attachmentPointRagdollSpace = 0xbe4; // GlobalTypes::Vector m_attachmentPointRagdollSpace; |  Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_bShouldDetach = 0xbf0; // bool m_bShouldDetach; |  0xbf0 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bShouldDeleteAttachedActivationRecord = 0xc00; // bool m_bShouldDeleteAttachedActivationRecord; |  0xc00 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
