// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x578
			namespace CTestEffect /*: public CS2::server::CBaseEntity*/ {
				constexpr std::ptrdiff_t m_iLoop = 0x4a8; // int32_t m_iLoop; |  0x4a8 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_iBeam = 0x4ac; // int32_t m_iBeam; |  0x4ac | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_pBeam = 0x4b0; // GlobalTypes::CHandle  | Schema_FixedArray | Size: 0x60
				constexpr std::ptrdiff_t m_flBeamTime = 0x510; // GlobalTypes::GameTime_t[24]  | Schema_FixedArray | Size: 0x900
				constexpr std::ptrdiff_t m_flStartTime = 0x570; // entity2::GameTime_t  | Schema_DeclaredClass | Size: 0x4
			}
		}
	}
}
