// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x810
			namespace CTextureBasedAnimatable /*: public CS2::server::CBaseModelEntity*/ {
				constexpr std::ptrdiff_t m_bLoop = 0x7d8; // bool m_bLoop; |  0x7d8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_flFPS = 0x7dc; // float32 m_flFPS; |  0x7dc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_hPositionKeys = 0x7e0; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_hRotationKeys = 0x7e8; // GlobalTypes::CStrongHandle<resourcesystem::InfoForResourceTypeCTextureBase>  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_vAnimationBoundsMin = 0x7f0; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vAnimationBoundsMax = 0x7fc; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_flStartTime = 0x808; // float32 m_flStartTime; |  0x808 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flStartFrame = 0x80c; // float32 m_flStartFrame; |  0x80c | Schema_Builtin | Size: 0x4
			}
		}
	}
}
