// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0xA80
			namespace CTriggerLook /*: public CS2::server::CTriggerOnce*/ {
				constexpr std::ptrdiff_t m_hLookTarget = 0x9e8; // server::CHandle< server::CBaseEntity > m_hLookTarget; |  Schema_Atomic | Size: 0x4
				constexpr std::ptrdiff_t m_flFieldOfView = 0x9ec; // float32 m_flFieldOfView; |  0x9ec | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flLookTime = 0x9f0; // float32 m_flLookTime; |  0x9f0 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flLookTimeTotal = 0x9f4; // float32 m_flLookTimeTotal; |  0x9f4 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flLookTimeLast = 0x9f8; // entity2::GameTime_t m_flLookTimeLast; |  Schema_DeclaredClass | Size: 0x4
				constexpr std::ptrdiff_t m_flTimeoutDuration = 0x9fc; // float32 m_flTimeoutDuration; |  0x9fc | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_bTimeoutFired = 0xa00; // bool m_bTimeoutFired; |  0xa00 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bIsLooking = 0xa01; // bool m_bIsLooking; |  0xa01 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_b2DFOV = 0xa02; // bool m_b2DFOV; |  0xa02 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bUseVelocity = 0xa03; // bool m_bUseVelocity; |  0xa03 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bTestOcclusion = 0xa04; // bool m_bTestOcclusion; |  0xa04 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bTestAllVisibleOcclusion = 0xa05; // bool m_bTestAllVisibleOcclusion; |  0xa05 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_OnTimeout = 0xa08; // entity2::CEntityIOOutput m_OnTimeout; |  Schema_DeclaredClass | Size: 0x28
				constexpr std::ptrdiff_t m_OnStartLook = 0xa30; // entity2::CEntityIOOutput m_OnStartLook; |  Schema_DeclaredClass | Size: 0x28
				constexpr std::ptrdiff_t m_OnEndLook = 0xa58; // entity2::CEntityIOOutput m_OnEndLook; |  Schema_DeclaredClass | Size: 0x28
			}
		}
	}
}
