// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace server {
			// Class size: 0x8C8
			namespace CTriggerPush /*: public CS2::server::CBaseTrigger*/ {
				constexpr std::ptrdiff_t m_angPushEntitySpace = 0x890; // GlobalTypes::QAngle  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_vecPushDirEntitySpace = 0x89c; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
				constexpr std::ptrdiff_t m_bTriggerOnStartTouch = 0x8a8; // bool m_bTriggerOnStartTouch; |  0x8a8 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bUsePathSimple = 0x8a9; // bool m_bUsePathSimple; |  0x8a9 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_iszPathSimpleName = 0x8b0; // GlobalTypes::CUtlSymbolLarge  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_PathSimple = 0x8b8; // server::CPathSimple**  | Schema_Ptr | Size: 0x8
				constexpr std::ptrdiff_t m_splinePushType = 0x8c0; // uint32_t m_splinePushType; |  0x8c0 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
