// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace client {
		class C_BaseEntityAPI  {
		public:
			S2_PAD(0x8);
		};
		static_assert(sizeof(CS2::client::C_BaseEntityAPI) == 0x8, "C_BaseEntityAPI size should be 0x8");
	}
}
