// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/C_LateUpdatedAnimating.hpp>



namespace CS2 {
	namespace client {
		class C_CS2HudModelBase : public CS2::client::C_LateUpdatedAnimating {
		public:
			S2_PAD(0x30);
		};
		static_assert(sizeof(CS2::client::C_CS2HudModelBase) == 0x1220, "C_CS2HudModelBase size should be 0x1220");
	}
}
