// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/C_BaseEntity.hpp>



namespace CS2 {
	namespace client {
		class C_CSPetPlacement : public CS2::client::C_BaseEntity {
		public:
		};
		static_assert(sizeof(CS2::client::C_CSPetPlacement) == 0x5F8, "C_CSPetPlacement size should be 0x5F8");
	}
}
