// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/C_CS2HudModelBase.hpp>



namespace CS2 {
	namespace client {
		class C_CS2HudModelArms : public CS2::client::C_CS2HudModelBase {
		public:
			S2_PAD(0xd0);
		};
		static_assert(sizeof(CS2::client::C_CS2HudModelArms) == 0x12F0, "C_CS2HudModelArms size should be 0x12F0");
	}
}
