// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include "../Custom/GlobalTypes.hpp"
#endif


#include "C_BaseEntity.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_EnvDetailController : public CS2::client::C_BaseEntity {
		public:
			float32 m_flFadeStartDist; // 0x608 | Schema_Builtin | Size: 0x4
			float32 m_flFadeEndDist; // 0x60c | Schema_Builtin | Size: 0x4
		};
		static_assert(offsetof(CS2::client::C_EnvDetailController, m_flFadeStartDist) == 0x608, "m_flFadeStartDist in C_EnvDetailController should be at offset 0x608");
		static_assert(offsetof(CS2::client::C_EnvDetailController, m_flFadeEndDist) == 0x60C, "m_flFadeEndDist in C_EnvDetailController should be at offset 0x60C");
		static_assert(sizeof(CS2::client::C_EnvDetailController) == 0x610, "C_EnvDetailController size should be 0x610");
	}
}
