// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/C_BaseCSGrenade.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class C_HEGrenade : public CS2::client::C_BaseCSGrenade {
		public:
		};
		static_assert(sizeof(CS2::client::C_HEGrenade) == 0x2000, "C_HEGrenade size should be 0x2000");
	}
}
