// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/C_CSWeaponBaseGun.hpp>



namespace CS2 {
	namespace client {
		class C_WeaponM4A1Silencer : public CS2::client::C_CSWeaponBaseGun {
		public:
		};
		static_assert(sizeof(CS2::client::C_WeaponM4A1Silencer) == 0x1FC0, "C_WeaponM4A1Silencer size should be 0x1FC0");
	}
}
