// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/CLogicalEntity.hpp>
#include <SDK/entity2/CEntityIOOutput.hpp>



namespace CS2 {
	namespace client {
		class CBaseFilter : public CS2::client::CLogicalEntity {
		public:
			bool m_bNegated; // 0x5f8 | Schema_Builtin | Size: 0x1
			S2_PAD(0x7);
			entity2::CEntityIOOutput m_OnPass; // 0x600 | Schema_DeclaredClass | Size: 0x28
			entity2::CEntityIOOutput m_OnFail; // 0x628 | Schema_DeclaredClass | Size: 0x28
		};
		static_assert(offsetof(CS2::client::CBaseFilter, m_bNegated) == 0x5F8, "m_bNegated in CBaseFilter should be at offset 0x5F8");
		static_assert(offsetof(CS2::client::CBaseFilter, m_OnPass) == 0x600, "m_OnPass in CBaseFilter should be at offset 0x600");
		static_assert(offsetof(CS2::client::CBaseFilter, m_OnFail) == 0x628, "m_OnFail in CBaseFilter should be at offset 0x628");
		static_assert(sizeof(CS2::client::CBaseFilter) == 0x650, "CBaseFilter size should be 0x650");
	}
}
