// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/CBodyComponentSkeletonInstance.hpp>



namespace CS2 {
	namespace client {
		class CBodyComponentBaseModelEntity : public CS2::client::CBodyComponentSkeletonInstance {
		public:
		};
		static_assert(sizeof(CS2::client::CBodyComponentBaseModelEntity) == 0x5B0, "CBodyComponentBaseModelEntity size should be 0x5B0");
	}
}
