// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CCSGO_WingmanIntroCharacterPosition.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CCSGO_WingmanIntroCounterTerroristPosition : public CS2::client::CCSGO_WingmanIntroCharacterPosition {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		static_assert(sizeof(CS2::client::CCSGO_WingmanIntroCounterTerroristPosition) == 0x13A8, "CCSGO_WingmanIntroCounterTerroristPosition size should be 0x13A8");

#endif
	}
}
