// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CPlayer_MovementServices.hpp>



namespace CS2 {
	namespace client {
		class CCSObserver_MovementServices : public CS2::client::CPlayer_MovementServices {
		public:
		};
		static_assert(sizeof(CS2::client::CCSObserver_MovementServices) == 0x238, "CCSObserver_MovementServices size should be 0x238");
	}
}
