// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include <SDK/client/CBaseFilter.hpp>





using namespace GlobalTypes;
namespace CS2 {
	namespace client {
		class CFilterAttributeInt : public CS2::client::CBaseFilter {
		public:
			GlobalTypes::CUtlSymbolLarge m_sAttributeName; // 0x650 | Schema_Atomic | Size: 0x8
		};
		static_assert(offsetof(CS2::client::CFilterAttributeInt, m_sAttributeName) == 0x650, "m_sAttributeName in CFilterAttributeInt should be at offset 0x650");
		static_assert(sizeof(CS2::client::CFilterAttributeInt) == 0x658, "CFilterAttributeInt size should be 0x658");
	}
}
