// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace client {
		class CNetworkOriginQuantizedVector  {
		public:
			S2_PAD(0x10);
			GlobalTypes::CNetworkedQuantizedFloat m_vecX; // 0x10 | Schema_Atomic | Size: 0x8
			GlobalTypes::CNetworkedQuantizedFloat m_vecY; // 0x18 | Schema_Atomic | Size: 0x8
			GlobalTypes::CNetworkedQuantizedFloat m_vecZ; // 0x20 | Schema_Atomic | Size: 0x8
		};
		static_assert(offsetof(CS2::client::CNetworkOriginQuantizedVector, m_vecX) == 0x10, "m_vecX in CNetworkOriginQuantizedVector should be at offset 0x10");
		static_assert(offsetof(CS2::client::CNetworkOriginQuantizedVector, m_vecY) == 0x18, "m_vecY in CNetworkOriginQuantizedVector should be at offset 0x18");
		static_assert(offsetof(CS2::client::CNetworkOriginQuantizedVector, m_vecZ) == 0x20, "m_vecZ in CNetworkOriginQuantizedVector should be at offset 0x20");
		static_assert(sizeof(CS2::client::CNetworkOriginQuantizedVector) == 0x28, "CNetworkOriginQuantizedVector size should be 0x28");
	}
}
