// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/CNmEventConsumer.hpp>



namespace CS2 {
	namespace client {
		class CNmEventConsumerAttributes : public CS2::client::CNmEventConsumer {
		public:
			S2_PAD(0x40);
		};
		static_assert(sizeof(CS2::client::CNmEventConsumerAttributes) == 0x50, "CNmEventConsumerAttributes size should be 0x50");
	}
}
