// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace client {
		enum CSWeaponSilencerType : std::uint32_t {
			CSWeaponSilencerType_WEAPONSILENCER_DETACHABLE = 0x1,
			CSWeaponSilencerType_WEAPONSILENCER_INTEGRATED = 0x2,
			CSWeaponSilencerType_WEAPONSILENCER_NONE = 0x0
		};
	}
}