// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/client/HitGroup_t.hpp>



namespace CS2 {
	namespace client {
		class DestructibleHitGroupToDestroy_t  {
		public:
			client::HitGroup_t m_nHitGroup; // 0x0 | Schema_DeclaredEnum | Size: 0x4
			int32_t m_nMaxDamageLevel; // 0x4 | Schema_Builtin | Size: 0x4
		};
		static_assert(offsetof(CS2::client::DestructibleHitGroupToDestroy_t, m_nHitGroup) == 0x0, "m_nHitGroup in DestructibleHitGroupToDestroy_t should be at offset 0x0");
		static_assert(offsetof(CS2::client::DestructibleHitGroupToDestroy_t, m_nMaxDamageLevel) == 0x4, "m_nMaxDamageLevel in DestructibleHitGroupToDestroy_t should be at offset 0x4");
		static_assert(sizeof(CS2::client::DestructibleHitGroupToDestroy_t) == 0x8, "DestructibleHitGroupToDestroy_t size should be 0x8");
	}
}
