// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace client {
		class EntitySpottedState_t  {
		public:
			S2_PAD(0x8);
			bool m_bSpotted; // 0x8 | Schema_Builtin | Size: 0x1
			S2_PAD(0x3);
			uint32_t m_bSpottedByMask[2]; // 0xc | Schema_FixedArray | Size: 0x8
			S2_PAD(0x4); // End padding
		};
		static_assert(offsetof(CS2::client::EntitySpottedState_t, m_bSpotted) == 0x8, "m_bSpotted in EntitySpottedState_t should be at offset 0x8");
		static_assert(offsetof(CS2::client::EntitySpottedState_t, m_bSpottedByMask) == 0xC, "m_bSpottedByMask in EntitySpottedState_t should be at offset 0xC");
		static_assert(sizeof(CS2::client::EntitySpottedState_t) == 0x18, "EntitySpottedState_t size should be 0x18");
	}
}
