// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>




namespace CS2 {
	namespace client {
		class ISkeletonAnimationController  {
		public:
			S2_PAD(0x8);
		};
		static_assert(sizeof(CS2::client::ISkeletonAnimationController) == 0x8, "ISkeletonAnimationController size should be 0x8");
	}
}
