// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace client {
		enum vote_create_failed_t : std::uint32_t {
			vote_create_failed_t_VOTE_FAILED_CANNOT_KICK_ADMIN = 0xc,
			vote_create_failed_t_VOTE_FAILED_CANT_ROUND_END = 0x1f,
			vote_create_failed_t_VOTE_FAILED_CONTINUE = 0x21,
			vote_create_failed_t_VOTE_FAILED_DISABLED = 0x15,
			vote_create_failed_t_VOTE_FAILED_FAILED_RECENTLY = 0x8,
			vote_create_failed_t_VOTE_FAILED_FAILED_RECENT_CHANGEMAP = 0x10,
			vote_create_failed_t_VOTE_FAILED_FAILED_RECENT_KICK = 0xf,
			vote_create_failed_t_VOTE_FAILED_FAILED_RECENT_RESTART = 0x13,
			vote_create_failed_t_VOTE_FAILED_FAILED_RECENT_SCRAMBLETEAMS = 0x12,
			vote_create_failed_t_VOTE_FAILED_FAILED_RECENT_SWAPTEAMS = 0x11,
			vote_create_failed_t_VOTE_FAILED_GENERIC = 0x0,
			vote_create_failed_t_VOTE_FAILED_ISSUE_DISABLED = 0x5,
			vote_create_failed_t_VOTE_FAILED_MAP_NAME_REQUIRED = 0x7,
			vote_create_failed_t_VOTE_FAILED_MAP_NOT_FOUND = 0x6,
			vote_create_failed_t_VOTE_FAILED_MATCH_NOT_PAUSED = 0x19,
			vote_create_failed_t_VOTE_FAILED_MATCH_PAUSED = 0x18,
			vote_create_failed_t_VOTE_FAILED_MAX = 0x22,
			vote_create_failed_t_VOTE_FAILED_NEXTLEVEL_SET = 0x16,
			vote_create_failed_t_VOTE_FAILED_NOT_10_PLAYERS = 0x1b,
			vote_create_failed_t_VOTE_FAILED_NOT_IN_WARMUP = 0x1a,
			vote_create_failed_t_VOTE_FAILED_PLAYERNOTFOUND = 0xb,
			vote_create_failed_t_VOTE_FAILED_QUORUM_FAILURE = 0x4,
			vote_create_failed_t_VOTE_FAILED_RATE_EXCEEDED = 0x2,
			vote_create_failed_t_VOTE_FAILED_REMATCH = 0x20,
			vote_create_failed_t_VOTE_FAILED_SCRAMBLE_IN_PROGRESS = 0xd,
			vote_create_failed_t_VOTE_FAILED_SPECTATOR = 0xe,
			vote_create_failed_t_VOTE_FAILED_SWAP_IN_PROGRESS = 0x14,
			vote_create_failed_t_VOTE_FAILED_TEAM_CANT_CALL = 0x9,
			vote_create_failed_t_VOTE_FAILED_TIMEOUT_ACTIVE = 0x1c,
			vote_create_failed_t_VOTE_FAILED_TIMEOUT_EXHAUSTED = 0x1e,
			vote_create_failed_t_VOTE_FAILED_TIMEOUT_INACTIVE = 0x1d,
			vote_create_failed_t_VOTE_FAILED_TOO_EARLY_SURRENDER = 0x17,
			vote_create_failed_t_VOTE_FAILED_TRANSITIONING_PLAYERS = 0x1,
			vote_create_failed_t_VOTE_FAILED_WAITINGFORPLAYERS = 0xa,
			vote_create_failed_t_VOTE_FAILED_YES_MUST_EXCEED_NO = 0x3
		};
	}
}