// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include <SDK/GlobalTypes.hpp>
#else
	#include <Custom/GlobalTypes.hpp>
#endif





namespace CS2 {
	namespace client {
		class WaterWheelFrictionScale_t  {
		public:
			float32 m_flFractionOfWheelSubmerged; // 0x0 | Schema_Builtin | Size: 0x4
			float32 m_flFrictionScale; // 0x4 | Schema_Builtin | Size: 0x4
		};
		static_assert(offsetof(CS2::client::WaterWheelFrictionScale_t, m_flFractionOfWheelSubmerged) == 0x0, "m_flFractionOfWheelSubmerged in WaterWheelFrictionScale_t should be at offset 0x0");
		static_assert(offsetof(CS2::client::WaterWheelFrictionScale_t, m_flFrictionScale) == 0x4, "m_flFrictionScale in WaterWheelFrictionScale_t should be at offset 0x4");
		static_assert(sizeof(CS2::client::WaterWheelFrictionScale_t) == 0x8, "WaterWheelFrictionScale_t size should be 0x8");
	}
}
