// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CPulseCell_BaseFlow.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace pulse_runtime_lib {
		class CPulseCell_BaseYieldingInflow : public CS2::pulse_runtime_lib::CPulseCell_BaseFlow {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		static_assert(sizeof(CS2::pulse_runtime_lib::CPulseCell_BaseYieldingInflow) == 0x48, "CPulseCell_BaseYieldingInflow size should be 0x48");

#endif
	}
}
