// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace pulse_runtime_lib {
		enum PulseCursorExecResult_t : std::uint32_t {
			PulseCursorExecResult_t_Canceled = 0x1,
			PulseCursorExecResult_t_Failed = 0x2,
			PulseCursorExecResult_t_OngoingNotify = 0x3,
			PulseCursorExecResult_t_Succeeded = 0x0
		};
	}
}