// generated - do not edit!
enum animgraphlib_AnimParamVectorType_t {
	ANIMPARAM_VECTOR_TYPE_DIRECTION_LS = 0x4,
	ANIMPARAM_VECTOR_TYPE_DIRECTION_WS = 0x3,
	ANIMPARAM_VECTOR_TYPE_NONE = 0x0,
	ANIMPARAM_VECTOR_TYPE_POSITION_LS = 0x2,
	ANIMPARAM_VECTOR_TYPE_POSITION_WS = 0x1
}