// generated - do not edit!
enum animgraphlib_CAnimationGraphVisualizerPrimitiveType {
	ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Axis = 0x4,
	ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Line = 0x2,
	ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Pie = 0x3,
	ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Sphere = 0x1,
	ANIMATIONGRAPHVISUALIZERPRIMITIVETYPE_Text = 0x0
}