// generated - do not edit!
enum animgraphlib_StateActionBehavior {
	STATETAGBEHAVIOR_ACTIVE_WHILE_CURRENT = 0x0,
	STATETAGBEHAVIOR_ACTIVE_WHILE_FULLY_BLENDED = 0x4,
	STATETAGBEHAVIOR_FIRE_ON_ENTER = 0x1,
	STATETAGBEHAVIOR_FIRE_ON_ENTER_AND_EXIT = 0x3,
	STATETAGBEHAVIOR_FIRE_ON_EXIT = 0x2
}