// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/animgraphlib/CMotionNode.hpp>



namespace CS2 {
	namespace animgraphlib {
		class CMotionNodeBlend1D : public CS2::animgraphlib::CMotionNode {
		public:
			// GlobalTypes::CUtlVector< animgraphlib::MotionBlendItem > m_blendItems; // 0x28 | Schema_Atomic | Size: 0x18
			char  m_blendItems[0x18]; // 0x28 | Schema_Atomic | Size: 0x18
			int32_t m_nParamIndex; // 0x40 | Schema_Builtin | Size: 0x4
			S2_PAD(0x4); // End padding
		};
		static_assert(offsetof(CS2::animgraphlib::CMotionNodeBlend1D, m_blendItems) == 0x28, "m_blendItems in CMotionNodeBlend1D should be at offset 0x28");
		static_assert(offsetof(CS2::animgraphlib::CMotionNodeBlend1D, m_nParamIndex) == 0x40, "m_nParamIndex in CMotionNodeBlend1D should be at offset 0x40");
		static_assert(sizeof(CS2::animgraphlib::CMotionNodeBlend1D) == 0x48, "CMotionNodeBlend1D size should be 0x48");
	}
}
