// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#ifndef CUSTOM_GLOBAL_TYPES
	#include "../GlobalTypes.hpp"
#else
	#include <Custom/GlobalTypes.hpp>
#endif


#include "CPathAnimMotorUpdaterBase.hpp"





using namespace GlobalTypes;
namespace CS2 {
	namespace animgraphlib {
		class CPathAnimMotorUpdater : public CS2::animgraphlib::CPathAnimMotorUpdaterBase {
		public:
		};
#ifdef USE_STATIC_ASSERTS
		static_assert(sizeof(CS2::animgraphlib::CPathAnimMotorUpdater) == 0x28, "CPathAnimMotorUpdater size should be 0x28");

#endif
	}
}
