// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <SDK/GlobalTypes.hpp>

#include <SDK/animgraphlib/CAnimTagBase.hpp>



namespace CS2 {
	namespace animgraphlib {
		class CStringAnimTag : public CS2::animgraphlib::CAnimTagBase {
		public:
		};
		static_assert(sizeof(CS2::animgraphlib::CStringAnimTag) == 0x50, "CStringAnimTag size should be 0x50");
	}
}
