// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace animgraphlib {
		enum HandshakeTagState_t : std::uint8_t {
			HandshakeTagState_t_eActive = 0x1,
			HandshakeTagState_t_eInactive = 0x0,
			HandshakeTagState_t_eMomentarilyInactive = 0x2
		};
	}
}