// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

namespace CS2 {
	namespace animgraphlib {
		enum ResetCycleOption : std::uint32_t {
			ResetCycleOption_Beginning = 0x0,
			ResetCycleOption_FixedValue = 0x3,
			ResetCycleOption_InverseSourceCycle = 0x2,
			ResetCycleOption_SameCycleAsSource = 0x1,
			ResetCycleOption_SameTimeAsSource = 0x4
		};
	}
}