// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x38
			namespace CNmChainLookatNode_CDefinition /*: public CS2::animlib::CNmPassthroughNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_chainEndBoneID = 0x18; // GlobalTypes::CGlobalSymbol  | Schema_Atomic | Size: 0x8
				constexpr std::ptrdiff_t m_nLookatTargetNodeIdx = 0x20; // int16_t m_nLookatTargetNodeIdx; |  0x20 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_nEnabledNodeIdx = 0x22; // int16_t m_nEnabledNodeIdx; |  0x22 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_flBlendTimeSeconds = 0x24; // float32 m_flBlendTimeSeconds; |  0x24 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_nChainLength = 0x28; // uint8_t m_nChainLength; |  0x28 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bIsTargetInWorldSpace = 0x29; // bool m_bIsTargetInWorldSpace; |  0x29 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_chainForwardDir = 0x2c; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
			}
		}
	}
}
