// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x20
			namespace CNmConstVectorNode_CDefinition /*: public CS2::animlib::CNmVectorValueNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_value = 0x10; // GlobalTypes::Vector  | Schema_Atomic | Size: 0xc
			}
		}
	}
}
