// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x28
			namespace CNmRootMotionEvent /*: public CS2::animlib::CNmEvent*/ {
				constexpr std::ptrdiff_t m_flBlendTimeSeconds = 0x20; // float32 m_flBlendTimeSeconds; |  0x20 | Schema_Builtin | Size: 0x4
			}
		}
	}
}
