// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x20
			namespace CNmSpeedScaleBaseNode_CDefinition /*: public CS2::animlib::CNmPassthroughNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_nInputValueNodeIdx = 0x18; // int16_t m_nInputValueNodeIdx; |  0x18 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_flDefaultInputValue = 0x1c; // float32 m_flDefaultInputValue; |  0x1c | Schema_Builtin | Size: 0x4
			}
		}
	}
}
