// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x20
			namespace CNmTimeConditionNode_CDefinition /*: public CS2::animlib::CNmBoolValueNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_sourceStateNodeIdx = 0x10; // int16_t m_sourceStateNodeIdx; |  0x10 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_nInputValueNodeIdx = 0x12; // int16_t m_nInputValueNodeIdx; |  0x12 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_flComparand = 0x14; // float32 m_flComparand; |  0x14 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_type = 0x18; // animlib::CNmTimeConditionNode::ComparisonType_t  | Schema_DeclaredEnum | Size: 0x1
				constexpr std::ptrdiff_t m_operator = 0x19; // animlib::CNmTimeConditionNode::Operator_t  | Schema_DeclaredEnum | Size: 0x1
			}
		}
	}
}
