// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x20
			namespace CNmTargetInfoNode_CDefinition /*: public CS2::animlib::CNmFloatValueNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_nInputValueNodeIdx = 0x10; // int16_t m_nInputValueNodeIdx; |  0x10 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_infoType = 0x14; // animlib::CNmTargetInfoNode::Info_t  | Schema_DeclaredEnum | Size: 0x4
				constexpr std::ptrdiff_t m_bIsWorldSpaceTarget = 0x18; // bool m_bIsWorldSpaceTarget; |  0x18 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
