// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x38
			namespace CNmTargetSelectorNode_CDefinition /*: public CS2::animlib::CNmClipReferenceNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_optionNodeIndices = 0x10; // GlobalTypes::CUtlLeanVectorFixedGrowable  | Schema_Atomic | Size: 0x18
				constexpr std::ptrdiff_t m_flOrientationScoreWeight = 0x28; // float32 m_flOrientationScoreWeight; |  0x28 | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_flPositionScoreWeight = 0x2c; // float32 m_flPositionScoreWeight; |  0x2c | Schema_Builtin | Size: 0x4
				constexpr std::ptrdiff_t m_parameterNodeIdx = 0x30; // int16_t m_parameterNodeIdx; |  0x30 | Schema_Builtin | Size: 0x2
				constexpr std::ptrdiff_t m_bIgnoreInvalidOptions = 0x32; // bool m_bIgnoreInvalidOptions; |  0x32 | Schema_Builtin | Size: 0x1
				constexpr std::ptrdiff_t m_bIsWorldSpaceTarget = 0x33; // bool m_bIsWorldSpaceTarget; |  0x33 | Schema_Builtin | Size: 0x1
			}
		}
	}
}
