// generated - do not edit!
// generated by @xsip cs2 schema generator

#pragma once

#include <cstddef>

namespace CS2 {
	namespace SchemaOffsets {
		namespace animlib {
			// Class size: 0x18
			namespace CNmVirtualParameterVectorNode_CDefinition /*: public CS2::animlib::CNmVectorValueNode_CDefinition*/ {
				constexpr std::ptrdiff_t m_nChildNodeIdx = 0x10; // int16_t m_nChildNodeIdx; |  0x10 | Schema_Builtin | Size: 0x2
			}
		}
	}
}
